### ISSUE TITLE
quelques icônes n'apparaissent plus sur l'interface (v1)

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/Pangloss#104]
Sur la version actuelle de l'interface (v1), quelques images (icônes) n'apparaissent plus. 

Il y a celle des fichiers XML

![image](https://user-images.githubusercontent.com/6072524/93382501-7d3f3800-f862-11ea-9fd1-d23a350f9c2f.png)

et aussi l'icône des DOI
![image](https://user-images.githubusercontent.com/6072524/93382583-9942d980-f862-11ea-8bda-5c766c22f476.png)

et le bouton "Lecture" (et le petit bouton DOI pour les unités de premier niveau)
![image](https://user-images.githubusercontent.com/6072524/93382640-b1b2f400-f862-11ea-949b-b0166a3a3bc6.png)

"Effet secondaire" de la mise à jour PHP faite récemment ?

**Comment by sguillaume** [comment]
Bizarre, moi ça marche
<img width="869" alt="affichage" src="https://user-images.githubusercontent.com/6065936/93459212-ab179180-f8e1-11ea-8040-7d00e77aad50.png">
Pour ce qui est de l'icône play pour les phrases c'est normal qu'elle n'apparaisse pas. Cela signifie que le texte n'est pas synchronisé avec le son.

**Comment by alexis-michaud** [comment]
👍
