### ISSUE TITLE
Métadonnées Cocoon : des métadonnées présentes dans la base n'apparaissent pas dans la fiche exposée

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/Pangloss#105]
@BenjaminGalliot signale que deux ressources (audio+transcription) sont sans indication de locuteur. 

├── crdo-NRU_M31_NUM_CL.wav
├── crdo-NRU_M31_NUM_CL.xml
├── crdo-NRU_M31_TONES.wav
├── crdo-NRU_M31_TONES.xml

Les identifiants Cocoon sont : 

| fichier              | identifiant Cocoon                                             |  identifiant DOI |
|------------------|---------------------------------------------------------------|----------------------------------|
| crdo-NRU_M31_NUM_CL.wav | cocoon-44b54ca4-b066-3e50-9411-975ae0e44af4 |  |
| crdo-NRU_M31_NUM_CL.xml | cocoon-15122d4c-d49b-3fb6-bad1-5103a703c373 | https://doi.org/10.24397/pangloss-0004839 |
| crdo-NRU_M31_TONES.wav| cocoon-bb483285-dc13-3783-b4d9-7faed4e622de |  |
| crdo-NRU_M31_TONES.xml| cocoon-99058337-e29c-38ac-bd9c-11af68657b82 | https://doi.org/10.24397/pangloss-0004841 |

L'info "locuteur" manque dans [la fiche exposée (disponible en ligne)](https://cocoon.huma-num.fr/crdo_servlet/oai-pmh?verb=GetRecord&metadataPrefix=olac&identifier=oai:crdo.vjf.cnrs.fr:cocoon-15122d4c-d49b-3fb6-bad1-5103a703c373). Le collègue y est bien mentionné, mais dans son rôle de chercheur, et pas dans celui de locuteur.

```
<dc:contributor xsi:type="olac:role" olac:code="researcher">La, Mingqing</dc:contributor>
<dc:contributor xsi:type="olac:role" olac:code="transcriber">Michaud, Alexis</dc:contributor>
<dc:contributor xsi:type="olac:role" olac:code="annotator">Michaud, Alexis</dc:contributor>
<dc:contributor xsi:type="olac:role" olac:code="translator">Dobbs, Roselle</dc:contributor>
```

Pas de mention du `"speaker"`.

C'est bien le diable ! car la ressource a bien les infos en question : les métadonnées sont présentes dans la base Cocoon. Cf ci-dessous : 

![image](https://user-images.githubusercontent.com/6072524/94687240-4b32d900-032c-11eb-8585-69d2f37535de.png)

Ces métadonnées apparaissent bien dans l'interface de la collection Pangloss. 
![image](https://user-images.githubusercontent.com/6072524/94689160-d1501f00-032e-11eb-90ed-f0ea0b868974.png)

D'où vient le problème dans les métadonnées que Cocoon fournit lorsque le catalogue est téléchargé ? (Le fait de ne pas déclarer de langue pour l'info "locuteur" ne devrait pourtant pas faire planter ?)

**Comment by sguillaume** [comment]
Attention, le nom du speaker n'apparait que dans les métadonnées des ressources où il est présent (où on l'entend et le voit donc) à savoir dans les enregistrements audio ou vidéo.
Mais jamais dans les annotations (sauf erreur).
De la même manière, les nom des personnes qui font les transcriptions et traductions n'apparaissent que dans les métadonnées des annotations.

Cela répond ?

Je clos en supposant que oui :)

**Comment by alexis-michaud** [comment]
Ah compris ! Les 2 fichiers qui posent problème, sur l'ensemble du jeu de données na, sont les seuls qui sont conformes aux préconisations, en fait !!

**Comment by alexis-michaud** [comment]
Tous les autres ont l'indication de la locutrice dans les métadonnées des annotations
alors qu'en fait cette indication ne devrait pas y figurer !

**Comment by alexis-michaud** [comment]
@BenjaminGalliot va revoir son script en fonction. 

Quant à toiletter les métadonnées pour virer l'info locuteur ("speaker") de _toutes_ les fiches de métadonnées pour toutes les langues de Cocoon... 
... en veillant bien sûr à ce que l'info soit bien présente dans les métadonnées du fichier média correspondant ^^ ...
Bon courage :)

**Comment by sguillaume** [comment]
Oui. Il y a beaucoup d'autres choses à nettoyer.
Un documentaliste nous aiderait bien :p

**Comment by alexis-michaud** [comment]
C'est une demande qui ne paraît pas illégitime, à discuter avec des bibliothèques qui seraient prêtes à devenir partenaires du projet. A commencer par celles qui sont dans le périmètre de nos partenaires institutionnels & de nos tutelles ? Bibliothèque du centre Haudricourt, mais aussi BULAC, Direction des Bibliothèques de la Sorbonne Nouvelle, Bibliothèque Sainte-Geneviève...
