### ISSUE TITLE
interface Pangloss v2 : conflits entre menu déroulant et menu fixe

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/Pangloss#107]
Quand on est sur une page et qu'on veut changer la langue, le menu déroulant "langue" ( fr / en ) recouvre en partie le menu fixe (Qui sommes-nous ?  Corpus  Dictionnaires  Contact), et quand on clique, c'est l'action correspondant au menu fixe qui est réalisée, de sorte qu'on se retrouve dans la page Dictionnaire, au lieu de changer simplement de langue et rester sur la même page, pour l'exemple ci-dessous :

![image](https://user-images.githubusercontent.com/6072524/95901668-f6637980-0d93-11eb-8e37-2937291997aa.png)

**Comment by EdouardSombie** [comment]
Problème réglé
