### ISSUE TITLE
site Pangloss v2 : affichage page "Pangloss Labs"

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/Pangloss#108]
Actuellement, la page pangloss-labs, qui ne devrait s'afficher qu'en mode pro, ne s'affiche... qu'en mode non-pro. (Il n'y a pas de lien qui pointe vers elle, du coup, mais on peut forcer en demandant `pangloss-labs` sans la mention PRO.)

Sur l'interface d'admin pour cette page, seuls apparaissent les champs "français" et "anglais", ce qui n'est pas gênant pourvu qu'en coulisses ça soit bien considéré comme du PRO (modification à faire dans la base de données ?)

Merci++

**Comment by EdouardSombie** [comment]
Le problème pour la page "pangloss labs" est réglé.
Idem pour la page "outils".
Ces deux pages ne sont plus accessible en "forçant" le mode normal dans l'url
