### ISSUE TITLE
affichage licence sur page de consultation d'une ressource

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/Pangloss#109]
Les mentions légales signalent que : 

> Documents linguistiques
> La licence sous laquelle chacun des documents linguistiques de la collection Pangloss est placé est indiquée sur la page de consultation.

Mais ce n'est pas encore implémenté : la licence n'est pas affichée dans le volet de droite de la page où on consulte une ressource. 

@Doudou-git

**Comment by EdouardSombie** [comment]
J'ai ajouté un bloc affichant la licence de la ressource.
Si cette licence est une url, cette dernière est cliquable (lien externe)
