### ISSUE TITLE
Affichage des documents, mode "pro" et "non-pro"

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/Pangloss#111]
**Exposition des aménagements à faire pour l'affichage des documents :**

Etat au 21 décembre 2020 :
![image](https://user-images.githubusercontent.com/6072524/102789264-2aff3d00-43a4-11eb-96fd-9fc5c5c8869f.png)

(document : https://pangloss.cnrs.fr/ ... /corpus/show?lang=fr&mode=pro&oai_primary=cocoon-b7353e0a-4bb0-4262-b53e-0a4bb0e26214&oai_secondary=cocoon-5f66bd3a-c0a4-4c78-a6bd-3ac0a48c789b&optionTextTranscriptions=&optionTextTranslations=&optionSentenceTranscriptions=other&optionSentenceTranslations=fr&optionWordTranscriptions=other&optionWordTranslations=&optionMorphemeTranscriptions=other&optionMorphemeTranslations=fr&optionNotes=&optionWords=true )

1) L'affichage des traductions au niveau du mot devrait se faire **sous la transcription du niveau du mot**, et non de façon discontinue. Dans l'état actuel, la structure est : 
FORM au niveau du W
FORM au niveau des M
TRANSL au niveau des M
TRANSL au niveau des W

C'est compréhensible qu'un tel choix ait été fait, puisque c'est déjà comme ça que ça marchait pour le niveau S : la FORM au niveau S venait en premier, puis les gloses (W, M), et tout en bas, la traduction (TRANSL) au niveau S. Si c'était des poèmes on parlerait de "rimes embrassées" ! Mais séparer la FORM au niveau W de sa traduction (TRANSL) rend l'ensemble peu lisible. 

La structure est effectivement compliquée. Le niveau S marche "en rimes embrassées" (sa FORM en début de 'carte', sa TRANSL en fin de 'carte'). Par contre, pour les niveaux W et M, mieux vaudrait avoir des "rimes plates" : le niveau W, comportant la FORM puis les TRANSL ; puis le niveau M (pareil : FORM puis TRANSL). Ainsi, cette partie-là suit la hiérarchie des constituants.

Comme ci-dessous (exemple modifié manuellement sur image) :
![image](https://user-images.githubusercontent.com/6072524/102789759-d9a37d80-43a4-11eb-958f-d8bee0186ac8.png)

Après, il y a d'autres points à voir : notamment qu'afficher le niveau W **et** le niveau M a quelque chose de redondant, quand en fait le XML ne contient de FORM et de TRANSL qu'à un seul de ces deux niveaux. D'où le point 2 :

2) Il faudrait **poser une condition sur l'existence de traductions au niveau du mot**. Lors de l'ouverture (affichage par défaut) : afficher **les traductions qui existent** plutôt que des traductions concaténées.

Dans cet exemple : le document XML ne contient pas de traductions ni de formes au niveau W, semble-t-il. Du coup, par défaut, la traduction et la forme au niveau W  devraient être **décochées** au départ. Si l'utilisatrice coche la case "Traduction" au niveau W, on produit les traductions en concaténant les traductions du niveau M. Pareil si l'utilisatrice coche "Transcription des mots".

Autrement dit, l'affichage par défaut serait : 

![image](https://user-images.githubusercontent.com/6072524/102798548-93a0e680-43b1-11eb-8a59-6bc3999bbe7f.png)

La proposition de Séverine est un peu différente en ce qui concerne le choix par défaut : c'est le niveau W qui serait coché par défaut (en mode PRO), et le niveau M qui n'apparaîtrait que si on le coche : 

> j'aurais affiché directement le niveau mots [= la FORM au niveau W] avec tirets pour indiquer le découpage en morphèmes comme ça on a les 2 infos en 1 (et j'aurais fait idem pour les gloses [=TRANSL]).
Autrement dit, comme ci-dessous (mais en n'oubliant pas les séparateurs '-') : 
![image](https://user-images.githubusercontent.com/6072524/102811146-3adb4900-43c5-11eb-9a41-7924ec71c2ee.png)

C'est vrai que personnellement je préférerais afficher le niveau avec la granularité la plus fine (les morphèmes, M), parce que c'est visuellement le plus clair. La façon dont les morphèmes sont regroupés en mots, on la voit en regardant la transcription (FORM au niveau S). Concaténer des unités M, cela pourrait poser problème dans certaines langues, en fabriquant des "monstres" (pas bien méchants... mais des monstres quand même). Par exemple en français s'il y avait 'un désordre innommable' avec un mot (W) composé de _in-_, _nom_ et -_able_, ça irait tout à fait d'avoir une succession de 3 morphèmes, _in-_, _nom_, -_able_, mais ça serait très bof de concaténer ça en _in-nom-able_. Du coup on partirait d'abord sur un affichage des morphèmes **séparés**, avec chacun sa glose. Quelqu'un qui voudra voir les mots 'par concaténation' pourra cocher 'Transcription des mots' et 'Traduction des mots' (et, éventuellement, décocher le niveau M). Le choix d'afficher le niveau M par défaut (dans la configuration où les FORM et TRANSL ne sont pas renseignés au niveau W) est simplement une question d'option par défaut et pourrait éventuellement être modifié plus tard. 

Quand les niveaux M et W sont tous deux renseignés (contenant leurs FORM et TRANSL), on affiche tout par défaut (en mode pro). 

En mode non-pro : pas d'affichage des gloses, ni au niveau W ni au niveau M. 

3) Quand on crée le niveau W en concaténant les unités M qu'il contient (en l'absence de FORM et TRANSL fournies au niveau W) : veiller à bien ajouter le séparateur dont on est convenu : un tiret, par défaut ; et éviter qu'il n'y ait un double tiret si la FORM des morphèmes en contenait déjà un, ou un signe égal : dans ce cas on garde le tiret ou signe égal de la FORM.

4) Par défaut, en mode "grand public", ne pas afficher les gloses au niveau W ni M. 

En revanche, en mode pro, toutes les gloses sont affichées. Les gloses interlinéaires complètes constituent une information tout à fait cruciale.

5) Les infos de niveau "Texte entier" (transcription et traduction) sont **décochés** par défaut, dans les 2 modes (pro et non-pro). 

[Le présent 'billet' constitue une synthèse, établie le 21 décembre 2020, qui tient compte des échanges ci-dessous]

**Comment by sguillaume** [comment]
On pourrait par exemple.

Pour le mode pro, par défaut :
- affichage de toutes les transcriptions
- affichage des gloses 
- affichage de toutes les traductions ?
- pas d'affichage des notes

Pour le mode grand public, par défaut : 
- pas d'affichage des transcriptions
- pas d'affichage des gloses
- affichage de toutes les traductions 
- pas d'affichage des notes

Avec à chaque fois des petites boites qui permettent de voir ce qu'il y a d'autre.
Ainsi les personnes peuvent cocher ce qu'elles veulent si elles souhaitent afficher plus de choses.

Qu'en pensez vous ?

**Comment by alexis-michaud** [comment]
Ah, avis très différent ! Je serais pour afficher beaucoup plus : presque tout.

Mode pro, par défaut : comme ce que tu suggères (y compris : **afficher toutes les traductions**, oui), et **afficher les notes**. 

Mode grand public, par défaut : tout afficher sauf les notes. Autrement dit : 
- afficher les transcriptions, bien sûr (et toutes celles qu'on a : orthographe et notation 'savante' en alphabet phonétique), c'est important
- afficher (par défaut) les gloses, **même en mode grand public**. Ca montrera la richesse des documents (pour ceux parmi les documents qui sont riches de telles annotations, bien sûr), et ça fera découvrir, à des gens qui ne l'ont jamais vu, ce système simple mais particulièrement efficace. C'est pas difficile de décocher / 'éteindre' ce qu'on ne veut pas voir, tandis qu'à l'inverse, cliquer sur un bouton dont on ne sait pas ce qu'il va produire, ça ne va pas de soi. 
- pas d'affichage des notes : on est d'accord.

**Comment by sguillaume** [comment]
L'idée pour le grand public est que ce qu'ils verront quand ils consulteront les pages soit parlant pour eux.
Si on commence à tout afficher ils vont prendre peur.
Alors que s'ils ont une page claire dès le premier regard (transcription et traduction) ils auront sûrement envie ensuite de cocher d'autres cases qui les intrigueront pour voir ce qui n'est pas affiché au lieu de ne pas savoir ce qu'ils voient à le première consultation.

Voilà mon avis ! :)

**Comment by alexis-michaud** [comment]
OK tu m'as convaincu.

Serait-on d'accord pour l'affichage ci-dessous ?

Mode pro, par défaut : comme ce que tu suggères (y compris : **afficher toutes les traductions**, oui), mais aussi **afficher les notes**. 

Mode grand public, par défaut : tout afficher sauf les notes et les gloses (et les traductions & transcriptions au niveau du texte entier). Autrement dit, afficher les transcriptions et les traductions (**toutes**, n'est-ce pas? tous les types de transcriptions, et les traductions dans toutes les langues disponibles)

**Comment by sguillaume** [comment]
Moi je n'aurais pas affiché les notes pour le mode pro non plus car ça fait beaucoup de choses sur une page.
Mais pour le reste tout à fait d'accord avec toi ! :)

**Comment by alexis-michaud** [comment]
Alors entendu pour ne pas afficher les notes par défaut. 

@EdouardSombie @m8nli9ht à vous de jouer ?

**Comment by alexis-michaud** [comment]
La balle passe dans le camp de Matthew @m8nli9ht

**Comment by sguillaume** [comment]
Je n'aurais pas affiché la forme des mots et la forme des morphèmes si l'une est la concaténation de l'autre. Ça fait double affichage.
Je l'aurais laissé en option à cocher. 
Ou mieux j'aurais affiché directement le niveau mots avec tirets pour indiquer le découpage en morphèmes comme ça on a les 2 infos en 1 (et j'aurais fait idem pour les gloses). Mais je crois que ma dernière proposition ne te plaît pas Alexis.
Ce que je n'aime pas c'est la redondance qui fait fouilli et perd les gens. 
Alors qu'en case a cocher ils savent au moins a quoi correspond ce qu'ils font apparaître surtout su ça parait être en double (alors qu'on ne sait pas a quoi correspond ce qui est déjà coché et donc visible). 

Et j'aurais affiché en noir les traductions et  mis un écart entre elles pour plus de lisibilité.

**Comment by alexis-michaud** [comment]
Ticket clôturé : réparti entre #128, https://github.com/CNRS/eastlingplayer/issues/27 et autres tickets.
