### ISSUE TITLE
bug légende photos

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/Pangloss#112]
Quand j'indique les légendes des photos en oubykh : pour la photo de M. Tevfik Esenç, j'indique : 
Tevfik Esenç à l'âge de 57 ans (en 1962)
Tevfik Esenç at age 57 (year 1962)

Ca enregistre, tout va bien... mais les champs sont intervertis. 
- ce qui a été saisi comme champ "anglais" apparaît dans le champ "français"
- le champ "anglais" se trouve tronqué : 
Tevfik Esenç at age 57 (year 1962)
Tevfik Esenç

Le bug se reproduit à chaque fois que je refais la manip'. 

Un souci avec la cédille ? 

Il serait souhaitable que les légendes des photos puissent utiliser tout l'Unicode, bien sûr

Merci bcp ! 

![image](https://user-images.githubusercontent.com/6072524/96884678-1117ab80-1482-11eb-979b-54ef7aed6dcf.png)

@EdouardSombie

**Comment by EdouardSombie** [comment]
Problème réglé.
Il va sans dire que le contenu accepte tous les caractères :)
