### ISSUE TITLE
Liste des choses à faire pour le basculement vers le nouveau site

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/Pangloss#113]
L'ouverture au public du nouveau site est maintenant prévue pour le **15 janvier 2021**. 

Pour que la transition se passe au mieux, peut-être serait-il utile de constituer ici une liste des tâches à effectuer, de façon à n'en oublier aucune ?

- modifier les liens dans les pages HTML de chaque corpus, de façon à ce que les liens vers les images et autres liens internes au site pointent bien vers la nouvelle adresse (pangloss.cnrs.fr/) et non vers l'adresse provisoire où le site se trouve actuellement

- modifier les métadonnées associées aux DOI, de façon à ce que les DOI soient interprétés de façon à envoyer au nouveau site un lien rédigé avec la bonne syntaxe pour affichage, y compris le numéro de phrase ou mot.  
Exemples pour tests : 

   - texte :
https://doi.org/10.24397/pangloss-0000658#S9 
   - liste de mots :
https://doi.org/10.24397/pangloss-0004845#W25

**Comment by sguillaume** [comment]
- Edouard a surement déjà prévu que tout ce qui est V2 dans les urls disparaitra lorsque le site sera mis en ligne officiellement. Edouard ?

- Et les DOI pointent déjà vers pangloss.cnrs.fr

**Comment by EdouardSombie** [comment]
Oui, je confirme :)
Pour faire simple, on remplacera toutes les occurences de "https://pangloss.cnrs.fr/v2/" par "https://pangloss.cnrs.fr/" dans les champs de la base de données.
Cela ne nous empêchera pas de faire un petit tour de vérification !
J'aurai également deux changements à faire dans le script php.

**Comment by sguillaume** [comment]
Ok super !
