### ISSUE TITLE
site Pangloss v2 : titre des pages HTML à revoir

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/Pangloss#114]
Actuellement : 

`<title>Pangloss | Collection - yongning na corpus - Le mariage de la soeur (version 1)</title>`

(identifiants de cet exemple : `show?lang=fr&oai_primary=cocoon-3dd9341b-647a-33d3-b0fd-2b0ab0e7f638&oai_secondary=cocoon-46ae2130-95ad-342d-9606-ef3d47594bee`)

C'est un peu un mélange entre français et anglais :smiley:

La barre verticale serait à mettre après le nom complet de la collection. Ca donnerait, pour le français : 
`<title>Collection Pangloss | corpus yongning na - Le mariage de la soeur (version 1)</title>`

et pour l'anglais : 
`<title>Pangloss Collection | Yongning Na corpus - Sister: The sister's wedding (version 1)</title>`

Pour l'anglais c'est bon, il y a juste la barre verticale à déplacer. Pour le français : ordre des mots à changer ("corpus" vient en premier) et bien veiller aux majuscules \& minuscules.

**Comment by EdouardSombie** [comment]
Fait :)
