### ISSUE TITLE
fichiers électroglottographiques : ce ne sont pas des annotations

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/Pangloss#115]
(ticket déplacé depuis [le dépôt du lecteur Eastling](https://github.com/CNRS/eastlingplayer/issues/14))

Un fichier électroglottographique, c'est un signal WAV de format identique à l'audio, mais de contenu différent (signal enregistré en faisant passer un courant de très basse intensité et de très haute fréquence entre 2 électrodes posées de part et d'autre du larynx). 

Dans la version actuelle du lecteur Eastling (27 octobre), ça s'affiche comme une annotation

![image](https://user-images.githubusercontent.com/6072524/97356821-1ff2c980-1899-11eb-8077-9967ca7c8620.png)

(et du coup la page est en blanc)

C'est un fichier qu'on peut télécharger : il n'y a pas lieu d'en donner un affichage particulier en ligne. Les gens que ça intéresse téléchargent le fichier et l'analysent avec l'outil de leur choix, par exemple les outils du dépôt [Covarep](https://github.com/covarep/covarep).

Exemple : 
oai_primary=cocoon-b3b0112a-e6bb-3ea7-b2f8-9d838aa172e2
&oai_secondary=cocoon-390794f4-15ff-3a78-8bcf-9580614ff98e

&optionGlosses=&optionNotes=true&optionTranscriptions=&optionTranslations=&optionWholeTranscriptions=false&optionWholeTranslations=&optionWords=false

@Doudou-git

**Comment by EdouardSombie** [comment]
Yo, c'est réglé, non ?
Il faut mettre un autre terme que 'Annotation 1' dans le bloc 'Téléchargements' pour les fichiers egg ?
Si oui, lequel ?

**Comment by alexis-michaud** [comment]
En effet, il faudrait indiquer "Signal électroglottographique" (en anglais: "Electroglottographic signal") au lieu de "annotation n"
![image](https://user-images.githubusercontent.com/6072524/103036697-aad70400-456a-11eb-87c6-81b68f63ff5d.png)

Merci bcp !

**Comment by EdouardSombie** [comment]
Fait, à traduire dans l'admin
