### ISSUE TITLE
page "Contact" du site v2

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/Pangloss#116]
Qu'y mettre ? Un formulaire de contact ? L'adresse courriel pangloss@cnrs.fr ?

**Comment by EdouardSombie** [comment]
Oui on peut mettre un formulaire de contact.
Quels champs vous voudriez ?
En plus de l'adresse email, il faut mettre une adresse physique, non ?
Fais-moi la liste et je fais la page :)

**Comment by sguillaume** [comment]
Pour la page contact, 

- Un formulaire peut être bien
Avec un champ du style "sujet" et un champ "message"
(Il nous faut aussi le mail de la personne pour pouvoir lui répondre)
Ce formulaire enverrait un mail à une ou plusieurs personnes.

- Mais il faut absolument mettre aussi une adresse mail visible pour les personnes qui préfèreraient écrire un mail (et par exemple mettre des choses en pièces jointes).
Quand on envoie un mail on a une trace de ce que l'on a écrit ce qui n'est pas le cas pour le formulaire donc de nombreuses personnes peuvent préférer le mail.

Qu'en pensez vous ?

**Comment by alexis-michaud** [comment]
Quels champs ? Quelque chose de simple : un champ "sujet", un champ "message", et le courriel de la personne pour pouvoir lui répondre.
Et une case 'Envoyer une copie du message à mon adresse courriel' (case cochée par défaut). Parce qu'on a une trace d'un courriel envoyé mais pas du contenu de ce que l'on a mis dans un formulaire.

Ce formulaire enverrait un mail à pangloss@cnrs.fr et aussi à l'adresse de @sguillaume (et aussi à la mienne). 

(En principe pangloss@cnrs.fr suffit car il renvoit à l'équipe, mais pour l'heure les tests ne sont pas entièrement concluants du coup mieux vaut envoyer aux 3 adresses.) 

Un avantage du formulaire étant qu'on risque moins de perdre un mail, dans les dialogues de serveurs. Si des disputes entre fournisseurs s'en mêlent, les envois de mails risquent d'être compliqués, tandis que ce qui est saisi sur le formulaire nous reste. 

Mais **la page du formulaire fournirait également une adresse visible 'en clair'**, pour les personnes qui préfèreraient écrire un mail (et par exemple mettre des choses en pièces jointes). Un 'mailto' avec pangloss@cnrs.fr comme destinataire, et @sguillaume en copie ?

Quant à l'adresse physique : pas sûr de voir l'utilité, mais si vous pensez que c'est une bonne idée, pourquoi pas, ça 'ancre' le projet sur le campus. Ce serait alors : 

Campus CNRS de Villejuif - centre André-Georges Haudricourt - laboratoire LACITO
bâtiment D, bureau 206
7 rue Guy Môquet 
94800 Villejuif

**Comment by EdouardSombie** [comment]
Salut 
Je m'occupe de faire la page d'ici la fin de semaine.
