### ISSUE TITLE
affichage intermittent des textes dans la version 2

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/Pangloss#117]
Sur mon ordinateur (aussi celui de Balthazar), affichage intermittent des textes dans la version 2 : tantôt rien ne s'affiche, tantôt ça s'affiche. 

Exemple : le document ci-dessous

show?lang=en&oai_primary=cocoon-8c729359-ac07-46bd-b293-59ac07b6bdb5&oai_secondary=cocoon-0dd84155-14a7-4115-9841-5514a781159a

Ca passe de l'un à l'autre (de façon qui semble aléatoire) en rechargeant la page. L'adresse (URL) n'est pas changée.

**Comment by alexis-michaud** [comment]
Navigateur : Chrome Version 86.0.4240.183 (Build officiel) (64 bits)
Même souci avec le navigateur Brave (Balthazar)

**Comment by alexis-michaud** [comment]
@EdouardSombie

**Comment by alexis-michaud** [comment]
L'affichage marche en revanche sans problème sur l'ordinateur de @m8nli9ht

**Comment by sguillaume** [comment]
Je ne sais pas si ça peut aider mais de mon côté rien ne s'affiche (mais tout est décoché par défaut) ni sur chrome ni sur firefox ni sur safari avec mon mac.
Par contre si je coche les cases ça s'affiche sur tous. Idem quand je recharge les pages.

**Comment by alexis-michaud** [comment]
Une image pour clarifier le problème : ça sera tout de suite plus clair. Quand rien ne s'affiche, c'est pas des boîtes vides, c'est vraiment... rien.

![image](https://user-images.githubusercontent.com/6072524/98832848-a1239200-243d-11eb-89a2-6513d2015217.png)

**Comment by m8nli9ht** [comment]
Sur celui là le problème vient du player et je l'ai corrigé a chaud pendant
notre visio, j'enverrai le build a Edouard pour l'intégrer.

Le mer. 11 nov. 2020 à 16:48, Alexis Michaud <notifications@github.com> a
écrit :
