### ISSUE TITLE
site v2 : carte des langues : vidéos transcrites n'apparaissent pas comme "Annotation"

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/Pangloss#118]
La carte des corpus permet de sélectionner les corpus qui ont des annotations (fichiers XML de transcription). 

![image](https://user-images.githubusercontent.com/6072524/99098688-a1589480-25d9-11eb-93bb-6d6b3e7c65d4.png)

Quand on coche "Avec annotation", le kakabé disparaît : 

![image](https://user-images.githubusercontent.com/6072524/99098740-b6cdbe80-25d9-11eb-8858-ba1d4be6e63c.png)

Pourtant, ce corpus (corpus/Kakabe?lang=fr&mode=pro) comporte bien des documents transcrits. 

Comment se fait le tri entre corpus avec et sans transcriptions ? Est-ce que ça ne regarde que les fichiers audio ?

**Comment by alexis-michaud** [comment]
('bug' relevé par @BenjaminGalliot )

**Comment by EdouardSombie** [comment]
Salut Alexis et Séverine,
Ce problème est dû au fait qu'un certain nombre de resources secondaires ont un champ "type" vide dans la base de données. 
@sguillaume : tu peux faire en sorte qu'il soit rempli ? Ou sinon, je peux leur affecter une valeur par défaut (text ou wordlist).

**Comment by sguillaume** [comment]
C'est déjà fait !
