### ISSUE TITLE
Pangloss v2, mode PRO : affichage identifiants depuis page consultation ressource

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/Pangloss#120]
Il s'agit d'afficher les identifiants (dans le volet de droite), afin que les utilisateurs n'aient pas besoin d'aller chercher les OAI tant bien que mal dans l'URL.

Un modèle possible, c'est le volet de droite de l'interface de publications scientifiques HAL : 
![image](https://user-images.githubusercontent.com/6072524/99182654-6cae1f80-2736-11eb-81ba-a0a208a175b3.png)

Les identifiants affichés : 
- ark
- oai
- hdl
- doi, pour faire bonne mesure (même si c'est redondant avec les icônes-boutons)

(Dans cet ordre-là ?)

Il faut afficher les identifiants pour les ressources primaires (enregistrements) et secondaires (annotations)

**Comment by alexis-michaud** [comment]
(recommandation de @BenjaminGalliot pour les informaticiens qui ont besoin des identifiants : ils passent par un DOI pour accéder à la ressource et il est souhaitable qu'ils puissent voir rapidement les identifiants)

**Comment by EdouardSombie** [comment]
Du coup, je crée un nouveau bloc dans la colonne de droite que j'appelle "identifiants" ?

**Comment by alexis-michaud** [comment]
Oui. Pour la version PRO du site.

**Comment by EdouardSombie** [comment]
C'est quoi l'identifiant hdl dont tu parles ?

**Comment by alexis-michaud** [comment]
HANDLE
Il figure dans les métadonnées COCOON
Si ça n'est pas dans les métadonnées transmises par Pangloss pour la base SQL, tu peux laisser tomber : ça fait "riche" de tout montrer mais s'il y a ARK et DOI et l'identifiant COCOON c'est déjà super !

**Comment by alexis-michaud** [comment]
Très beau boulot ! Merci @EdouardSombie 

![image](https://user-images.githubusercontent.com/6072524/100389093-b21ef680-302c-11eb-9a5e-6e102beaab9f.png)

**Comment by alexis-michaud** [comment]
Ah, juste un truc : pour l'identifiant OAI, celui de la ressource primaire a son préfixe "oai:crdo.vjf.cnrs.fr" tandis que celui de la ressource secondaire (annotation) ne l'a pas. Il est donc incomplet : il faudrait qu'un utilisateur qui récupère un identifiant OAI puisse l'employer tel quel, sans devoir y préfixer (comme on le fait nous tout naturellement) l'info concernant le réservoir de données qui contient la collection Pangloss.

@EdouardSombie encore une tâche pour toi, non ?

![image](https://user-images.githubusercontent.com/6072524/101692104-f91adc00-3a6f-11eb-9289-685cdab1f5de.png)

**Comment by EdouardSombie** [comment]
Fait :)
