### ISSUE TITLE
passage à https pour les liens vers fichiers dans Cocoon

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/Pangloss#121]
URL de référence vers le fichier original dans les métadonnées fournies pour le site v2 Pangloss : est tout en HTTP, il faut tout passer en HTTPS

**Comment by sguillaume** [comment]
Le site est en https donc sécurisé.
Je ne vois pas pourquoi ça détecte à un moment un site non sécurisé alors qu'on est toujours clairement en https.

**Comment by alexis-michaud** [comment]
C'est le lien fourni dans la base PHP / SQL qui est http:// semble-t-il ?
ce que tu envoies à Edouard
Il suffit de changer là-dedans, aucun souci côté Cocoon en effet

**Comment by alexis-michaud** [comment]
tu vois, c'est des liens comme 

[http://cocoon.huma-num.fr/data/simon/2TIB_Jeux-Reb2017-FINAL.xml](http://cocoon.huma-num.fr/data/simon/2TIB_Jeux-Reb2017-FINAL.xml)

**Comment by alexis-michaud** [comment]
(ici : ... `corpus/show?oai_primary=cocoon-7d6235a0-7b5a-416d-8077-01eae61efd28&oai_secondary=cocoon-b1d1b067-16fd-47db-b3c5-60ed2dd45045&optionWords=true&optionTranscriptions=%2Bother&optionTranslations=%2Bbo%2Bfr%2Ben&optionGlosses=&optionNotes=&optionWholeTranscriptions=false&optionWholeTranslations=` )

**Comment by sguillaume** [comment]
Je n'envoie aucun lien à Edouard et les seules url qui sont dans la base de données sont des urls cocoon de mon côté.

**Comment by alexis-michaud** [comment]
Ces URL sont en http ? ou en https?
par exemple comme ci-dessous ?
http://cocoon.huma-num.fr/data/simon/2TIB_Jeux-Reb2017-FINAL.xml

**Comment by sguillaume** [comment]
Elles sont en http. Comme pour tous les corpus de Cocoon. Mais ça renvoie à du https donc c'est sécurisé dans tous les cas.

**Comment by alexis-michaud** [comment]
Si on change juste l'adresse (la syntaxe) en remplaçant http par https (dans le lien), ça marche, non ?

Est-ce que ça ne serait pas une bonne idée de faire ainsi ? Cela suffirait pour éviter que ne s'affiche l'inquiétant message "Non sécurisé" dans les navigateurs. Ce message est en effet affiché pour les pages qui comportent des liens vers du non sécurisé (http). 

![image](https://user-images.githubusercontent.com/6072524/100442975-2c8d5c00-30a9-11eb-8acf-bd335da7678e.png)

**Comment by sguillaume** [comment]
J'ai écrit à Michel pour voir si l'on peut modifier ça dans cocoon au versement.
Ca n'est pas une bonne idée de bidouiller des modifs et de ne pas prendre les infos telles qu'elles sont déclarées (le jour où il y aura un changement ça peut poser des problèmes)

**Comment by alexis-michaud** [comment]
Super. 

Globalement, le passage à https, ça paraît quelque chose à faire, même dans les cas où il n'y aurait pas de risque de sécurité étant donné la façon dont fonctionnent les serveurs. Non ? 

Le simple affichage d'une mise en garde "Non sécurisé" peut légitimement inquiéter des visiteurs assez sensibilisés aux questions de sécurité informatique pour avoir appris à se méfier... mais pas assez calés pour faire la différence entre une mise en garde sans importance (qui peut être négligée sans réel danger) et un vrai danger.

**Comment by sguillaume** [comment]
Ca sera fait mais pas dans l'immédiat car ça implique des modifs dans les traitements.
Voilà !
