### ISSUE TITLE
ajustements graphisme Pangloss v2

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/Pangloss#122]
Le bandeau d'accueil pourrait-il être de taille un peu plus réduite ? 
![image](https://user-images.githubusercontent.com/6072524/101337522-0ff8dd00-387c-11eb-9187-f5634b9c774f.png)

de même pour le carrousel ? 
![image](https://user-images.githubusercontent.com/6072524/101337637-34ed5000-387c-11eb-85cf-dcd3b4a3d079.png)

Pour l'instant, ça occupe vraiment tout l'écran

**Comment by EdouardSombie** [comment]
Fait :)
