### ISSUE TITLE
Pangloss v2 : NaN

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/Pangloss#123]
![image](https://user-images.githubusercontent.com/6072524/101339278-7a128180-387e-11eb-814b-c06f2b14fc1d.png)

NaN = [Not a Number](https://fr.wikipedia.org/wiki/NaN), d'où il sort ? Rien dans le code. NaN est ajouté à la fin de chaque élément de premier niveau (W), à la fin de sa forme. En exposant.

Un _effet de bord_ dans l'interprétation d'un contenu Unicode ?? C'est pourtant un contenu sans surprise, qui finit par un /j/ tout normal, ASCII de chez ASCII.

`        <FORM kindOf="phono">tləːj</FORM>`

**Comment by alexis-michaud** [comment]
Est-ce que ça concerne le lecteur, @m8nli9ht ? ou l'intégration, @EdouardSombie ? ou les deux ??
Merci++

**Comment by m8nli9ht** [comment]
je me demande si ce n'est pas lié au #124 que je viens de corriger, peux-tu revérifier stp ?

**Comment by alexis-michaud** [comment]
Oui c'est réglé ! Super 
(document : https://pangloss.cnrs.fr/ ... /corpus/show?lang=fr&oai_primary=cocoon-2b7c4375-6145-3736-93d2-de60c7e28a9b&oai_secondary=cocoon-3b7748e7-ab4e-3771-b6e1-548d6dac3597&optionTextTranscriptions=&optionTextTranslations=&optionSentenceTranscriptions=&optionSentenceTranslations=&optionWordTranscriptions=phono&optionWordTranslations=vn&optionMorphemeTranscriptions=&optionMorphemeTranslations=&optionNotes=&optionWords=true )
![image](https://user-images.githubusercontent.com/6072524/102797309-cd70ed80-43af-11eb-80d5-9a122a789008.png)
