### ISSUE TITLE
listes de mots : boîte d'options vide

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/Pangloss#124]
![image](https://user-images.githubusercontent.com/6072524/102787298-26855500-43a1-11eb-8dbe-cb186e33a14e.png)

Exemple : https://pangloss.cnrs.fr/ ... /corpus/show?lang=fr&oai_primary=cocoon-bb37b586-9997-3081-9a2f-d06f0c2a3c71&oai_secondary=cocoon-75257e89-abfe-3a85-bee8-c393c13496e0

Serait-il possible d'indiquer la version du _build_ Eastling à mesure du développement ? par exemple par une montée de version dans GitHub ? Ainsi cela permettrait d'associer les notifications de bogues à une version précise, ce qui serait utile ?

**Comment by m8nli9ht** [comment]
MEA CULPA, j'avais relivré le parser (un peu tard un soir sans doute) en oubliant de "décommenter" 3 lignes de codes pour les wordlist, ça devrait refonctionner (sans livraison de build)
