### ISSUE TITLE
défilement vertical au fil de la lecture

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/Pangloss#125]
Le défilement vertical au fil de la lecture est en place pour les TEXT. Mais lors du défilement vertical des "boîtes" pour les phrases successives, la boîte se positionne en haut de l'écran... et du coup la transcription de la phrase est justement cachée par le bandeau :) (ainsi que le numéro de phrase et le DOI)
![image](https://user-images.githubusercontent.com/6072524/102878514-af0b0080-4448-11eb-95e0-f7a3a3e99a9d.png)

En outre, tant que tu (Edouard?) y seras à reparamétrer le positionnement vertical des cartons, ça serait bien de mettre le passage qu'on est en train d'écouter franchement plus bas, peut-être pas au milieu de l'écran, mais suffisamment bas pour que le défilement ne chasse pas aussitôt hors de l'écran (=hors de vue) la phrase qu'on vient d'écouter. S'il y a la place de mettre 3 boîtes ou plus, la boîte "courante" ce serait mieux que ce soit la 2e plutôt que la 1e.

(Impression globale du défilement : c'est bien, c'est fluide ; question d'ergonomie utilisateur, peut-être à approfondir côté intégration : @Edouard à toi de paramétrer et quand c'est opportun de faire tester à un petit cercle d'utilisateurs tu nous dis. )

**Comment by EdouardSombie** [comment]
Salut, il faudrait que ce soit le player qui décale le scroll de  350px vers le bas par rapport à ce qu'il fait actuellement.
@Matthew : tu peux le faire ? Ce sera plus propre que si je viens rajouter du js pour décaler les cartes vers le bas...

**Comment by alexis-michaud** [comment]
Juste pour signaler que c'est un peu urgent, à quelques jours de l'ouverture du site 
:sweat_smile: :sweat_smile: :sweat_smile: :sweat_smile:

**Comment by m8nli9ht** [comment]
Désolé je n'ai pas pu m'y mettre a cause des congés de Noël, je règle ça
demain ou jeudi.


Le mar. 29 déc. 2020 à 17:45, Alexis Michaud <notifications@github.com> a
écrit :

**Comment by alexis-michaud** [comment]
:relieved::relieved:
