### ISSUE TITLE
site Pangloss v2 : ne pas afficher les options 'non cliquables'

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/Pangloss#127]
Pour un texte comme celui-ci : oai:crdo.vjf.cnrs.fr:cocoon-a682c31e-594b-3a5c-8419-73e85204f763 (identifiant annotation), il n'y a que la FORM au niveau S. Dans un cas comme celui-là, **il ne faut pas afficher diverses options qui ne sont en fait pas disponibles**. La boîte ci-dessous propose : 

- Traduction du texte
- Traduction des phrases
- Transcription des mots
- Traduction des mots
- Transcription des morphèmes
- Traduction des morphèmes
- Mot à mot
- Notes

alors que rien de tout ça n'est disponible.
![image](https://user-images.githubusercontent.com/6072524/103037345-ede5a700-456b-11eb-822e-50492b5f5943.png)

La boîte d'options d'affichage ne devrait contenir que des options utiles : ce qui est réellement proposé.
![image](https://user-images.githubusercontent.com/6072524/103037569-6ba9b280-456c-11eb-9f2a-a3507412f8bc.png)
(exemple bricolé en mode image)

De même pour toutes les autres configurations : pour un texte qui ne comporte pas de notes, on ne fait pas figurer 'Notes', etc. 

A gérer dans le lecteur ? et/ou dans l'intégration web ? à nouveau la question à @EdouardSombie @m8nli9ht !

**Comment by EdouardSombie** [comment]
C'est plutôt au niveau du lecteur que ça se joue :)

**Comment by alexis-michaud** [comment]
@m8nli9ht à toi de jouer !

**Comment by m8nli9ht** [comment]
ok traité
