### ISSUE TITLE
Réduire encore le bandeau du haut ?

### ISSUE THREAD

**Issue by sguillaume** [CNRS/Pangloss#130]
Un retour utilisateur :
"Le bandeau du haut qui se réduit quand on descend dans la page pourrait être réduit dès le départ car la taille de ce qui est écrit est à peine réduite."

**Comment by alexis-michaud** [comment]
> "la taille de ce qui est écrit est à peine réduite"

En effet, c'est le logo qui change de taille, le reste est stable (et c'est mieux que ça soit stable !)

Personnellement je n'aime pas trop le côté dynamique : les changements dans l'affichage quand on se déplace sur la page. Et un bandeau du haut discret paraît mieux, pour un accès facilité au contenu. 

A discuter à tête reposée avec d'autres utilisateurs ?
