### ISSUE TITLE
Hyperliens sur logos

### ISSUE THREAD

**Issue by sguillaume** [CNRS/Pangloss#133]
Retour d'un utilisateur : 
Sur le bas de la page https://pangloss.cnrs.fr/v2/
"Il faudrait qu'un hyperlien accompagne chaque logo"

**Comment by alexis-michaud** [comment]
Oui, c'est une idée qui vient spontanément : rendre les liens cliquables
mais Non, ça n'est pas une bonne idée :smiley: On en avait parlé avec Voltajazz : clairement, ça ne paraît pas souhaitable de donner aux visiteurs des liens externes à droite et à gauche. Il s'agit d'institutions faciles à trouver sur internet, pas de souci pour leur visibilité. En revanche il faut que les clics sur le site donnent accès aux contenus du site et n'envoient pas l'internaute sur de tout autres sites.
