### ISSUE TITLE
Photos bandeau page d'accueil

### ISSUE THREAD

**Issue by sguillaume** [CNRS/Pangloss#138]
Question/ retour d'un utilisateur : 
"Page d’accueil, bandeau d'images: aucune d’image d'Océanie?"

**Comment by alexis-michaud** [comment]
Ah, on y reconnaît le vigoureux et sympathique attachement de chacun.e à son propre domaine d'étude :) Un particularisme... si bien partagé qu'il devient une caractéristique commune (voire un terrain d'entente ?) entre chercheuses/chercheurs.

Les ressources mises en valeur changeront au fil du temps, ça fait partie de l'éditorialisation. Grâce au travail de collecte de photos, maintenant bien entamé (et qui va se poursuivre), on a des surprises et des réserves.
