### ISSUE TITLE
Problème chargement annotation

### ISSUE THREAD

**Issue by sguillaume** [CNRS/Pangloss#141]
Retour utilisateur : 
"Plusieurs fois je remarque que lorsque j'ouvre un
texte avec annotation [à partir de la liste du
corpus], l'annotation ne se charge pas du premier
coup, et donc la page reste blanche (sauf le titre +
le fichier audio);
il faut que je recharge (F5) pour que l'annotation
apparaisse.
C'est embêtant, car beaucoup de lecteurs ne
penseront pas à recharger la page."

**Comment by alexis-michaud** [comment]
Affichage de textes sans chronocodes : bien vu. Un ticket a été ouvert [ici](https://github.com/CNRS/eastlingplayer/issues/46)

Bogue sporadique de page blanche, nécessité de recharger la page : en effet, problème constaté régulièrement sous Windows. Et en effet, un visiteur qui voit une page blanche et n'est pas familier des bizarreries du site conclut que ça ne marche pas, et est tenté d'aller voir ailleurs. 

Les développeurs sous Mac ne constatent pas ce souci, ce qui n'aide pas à le résoudre. 

@EdouardSombie ce serait possible que tu te procures un ordinateur sous Windows le temps de faire les recherches sur ce qui pourrait causer ce bogue contrariant ? Y aurait-il possibilité d'intégrer au site lui-même un script qui vérifie si la page (rendu graphique) est bien 'peuplée' des annotations désirées ? C'est un domaine que je ne connais pas, du coup j'ignore si une sorte de 'feedback' pourrait être envoyé par le moteur de rendu (WebKit?) de façon à s'assurer que ça s'affiche, et si ça n'est pas le cas, qu'un rapport d'erreur soit envoyé aux développeurs (cf. [ce ticket concernant le lecteur Eastling](https://github.com/CNRS/eastlingplayer/issues/1)).

**Comment by m8nli9ht** [comment]
Ok, de mon côté aussi je vais voir si je peux faire quelque chose.

**Comment by alexis-michaud** [comment]
Le même problème de rechargement se pose pour les PDF. Exemple [ici](https://doi.org/10.24397/pangloss-0004322).
![image](https://user-images.githubusercontent.com/6072524/104318211-62fb2b00-54df-11eb-947c-3a2891ff2273.png)
En rafraîchissant la page, l'affichage se fait : 
![image](https://user-images.githubusercontent.com/6072524/104318439-b40b1f00-54df-11eb-9ef9-5020890e423e.png)

En rafraîchissant plusieurs fois, tantôt ça apparaît, tantôt pas (annotation non affichée).

**Comment by alexis-michaud** [comment]
Question de novice : un script sur l'interface de consultation pourrait-il déterminer si une annotation s'affiche ou non sur l'écran ? 

Ca serait un **retour au sujet de l'affichage à l'écran**, qui permettrait de déterminer dans lequel des 2 cas de figure illustrés par les images ci-dessus on se trouve : annotation manquante, ou annotation affichée. 

Si un retour depuis le moteur de rendu pouvait permettre d'identifier que l'annotation "commandée" au lecteur Eastling n'y est pas, 
- le lecteur serait relancé (puisqu'il semble qu'il suffise de ça pour que l'affichage souhaité "vienne" : rafraîchir la page, parfois à plusieurs reprises)
- un rapport d'erreur serait envoyé aux développeurs, de façon à déterminer, par recoupement, les paramètres communs aux divers événements d'_annotation manquante_.

**Comment by EdouardSombie** [comment]
@Alexis : oui, on pourrait mettre un script pour relancer la page...
Mais ce serait mieux de faire autremement.
Je te propose de faire une série de tests en fin de journée ensemble pour identifier le souci. 17h30 ?

**Comment by alexis-michaud** [comment]
Alors le test c'est qu'on n'arrive plus à reproduire le bug ! 
La dernière version du lecteur Eastling qui a été livrée semble avoir résolu le souci. Ouf :)

**Comment by alexis-michaud** [comment]
Mauvaise nouvelle : le souci se présente à nouveau...
(Sous Windows, toujours)

**Comment by alexis-michaud** [comment]
Voici un rapport d'erreur un peu plus détaillé, pour analyser le souci. 

L'exemple est [celui-ci](https://pangloss.cnrs.fr/corpus/show?lang=en&mode=pro&oai_primary=cocoon-d7422cbf-af6d-3abd-a14e-256db16c4b3e&oai_secondary=cocoon-808ed143-df51-3954-bf98-74d17bd3bb2e&optionMorphemeTranscriptions=&optionMorphemeTranslations=&optionNotes=&optionSentenceTranscriptions=phono&optionSentenceTranslations=&optionTextTranscriptions=&optionTextTranslations=&optionWordTranscriptions=&optionWordTranslations=).

Quand l'annotation ne s'affiche pas, voici une image du code source HTML : 
![image](https://user-images.githubusercontent.com/6072524/106106111-59133200-6145-11eb-8a37-702063677075.png)

Quand l'annotation s'affiche, voici une image du code source HTML : 
![image](https://user-images.githubusercontent.com/6072524/106106283-9a0b4680-6145-11eb-8010-c6907c634dae.png)

La différence, c'est que quand ça ne charge pas, l'élément `div` est vide : `<div id="root"></div>`

La console fournit le rapport d'erreur suivant : 
![image](https://user-images.githubusercontent.com/6072524/106106623-1bfb6f80-6146-11eb-8f44-c7fd4f4c3711.png)

**Comment by m8nli9ht** [comment]
ok je regarde ça aujourd'hui

**Comment by alexis-michaud** [comment]
Super, tiens-nous au courant ! 
Dans la soirée, Edouard et moi comptions regarder aussi. Mais on ne t'en voudra pas si tu nous prends de vitesse en identifiant le souci et trouvant des remèdes avant :smiley:

**Comment by m8nli9ht** [comment]
J'ai livré, à tester et valider.

**Comment by alexis-michaud** [comment]
Le problème reste entier, hélas
![image](https://user-images.githubusercontent.com/6072524/106133655-dbabe980-6165-11eb-9edb-bca1d8f26a47.png)

Tu as fait quoi comme changements ?

**Comment by m8nli9ht** [comment]
ah ! c'est une autre ligne ça, je viens de faire également une modif ici, je livre ça dans la foulée

**Comment by m8nli9ht** [comment]
livré, à tester de nouveau !

**Comment by alexis-michaud** [comment]
L'est coriace, ce bogue-là ! 
Voici le nouveau _variant_ :
![image](https://user-images.githubusercontent.com/6072524/106149457-97771400-617a-11eb-93e0-dd5aab89b29c.png)

**Comment by alexis-michaud** [comment]
Tantôt l'erreur est étiquetée "77", comme ci-dessus (bouton blanc sur fond rouge), en haut à gauche). Tantôt "177" : 
![image](https://user-images.githubusercontent.com/6072524/106149828-fa68ab00-617a-11eb-9ff1-09b6a3aee0e5.png)

**Comment by m8nli9ht** [comment]
c'est la même erreur sur tes 2 screen, je regarde

**Comment by m8nli9ht** [comment]
j'ai testé une autre méthode. C'est livré, tu peux tester @alexis-michaud

**Comment by alexis-michaud** [comment]
Allez c'est parti : un chargement, 2, 3, 4, 5, 6, 7... jusqu'à 20
et plus aucune page blanche ! Il semble bien que ça marche. Bravo !!

Aurais-tu encore l'énergie d'établir un court bilan pour les annales / pour la doc' : pourquoi ça marchait sous Mac mais pas sous Windows, quel était le souci, et comment tu l'as résolu ? Ca serait une chouette façon de fêter la victoire sur ce bogue qui a donné bien du fil à retordre, non ?

**Comment by m8nli9ht** [comment]
Aucun rapport avec mac et windows à mon avis, j'ai juste fait en sorte que
les composants d'annotation ne se chargent que lorsque le player est bien
chargé dans la page.

Le jeu. 28 janv. 2021 à 18:05, Alexis Michaud <notifications@github.com> a
écrit :
