### ISSUE TITLE
Problème alignement transcription

### ISSUE THREAD

**Issue by sguillaume** [CNRS/Pangloss#142]
Retour utilisateur : 
"L'alignement de la transcription (phrase à phrase) n'est
pas homogène d'une phrase à
l'autre: tantôt la phrase commence à droite du bouton
lecture, tantôt en dessous du
bouton DOI.
Apparemment cela dépend de
la longueur de la phrase. Cf.
image. Peut-on harmoniser le
rendu ?"

**Comment by alexis-michaud** [comment]
Serait-il possible de donner l'exemple et l'image ? Merci

**Comment by sguillaume** [comment]
Voici un exemple : 
https://pangloss.cnrs.fr/v2/corpus/show?lang=fr&oai_primary=cocoon-b148006e-0711-3e50-9bf3-e997bc51b04c&oai_secondary=cocoon-128072b6-49b3-3edf-991d-6eca7d1bf238&optionMorphemeTranscriptions=&optionMorphemeTranslations=&optionNotes=&optionSentenceTranscriptions=other&optionSentenceTranslations=fr&optionTextTranscriptions=&optionTextTranslations=&optionWordTranscriptions=&optionWordTranslations=&optionWords=true

Et l'image : 
![image](https://user-images.githubusercontent.com/6065936/103477512-f174fb80-4dbf-11eb-859d-390ac5dea496.png)

**Comment by alexis-michaud** [comment]
@EdouardSombie Y aurait-il un moyen de renvoyer les boutons (S9, icône DOI, bouton de lecture) dans la marge à gauche ? (en dehors de la colonne principale)

Ainsi le texte occuperait toute la largeur de la colonne qui lui est consacrée, ce qui est optimal pour le bon affichage (pas seulement pour les longues phrases comme la S9, mais aussi pour de plus courtes, comme la S10 ou même des unités S d'un mot ou deux). Il y aurait un bon alignement vertical entre la ligne "transcription niveau S" et les autres lignes : mots, traductions de la phrase...

Et les outils seraient rassemblés dans la marge gauche. 

En fonction du travail que ça représente, et des urgences actuelles pour le basculement en v2, ça pourrait être reporté à un projet de "v3". En effet, en 2021 et au-delà, on va recevoir diverses demandes : souhaits d'aménagements et d'améliorations, pour lesquels une mise en forme / réflexion collective pourrait se faire aussi dans GitHub.

**Comment by alexis-michaud** [comment]
Fait, tout est dans la marge
