### ISSUE TITLE
Citation d'un corpus ?

### ISSUE THREAD

**Issue by sguillaume** [CNRS/Pangloss#146]
Retour utilisateur : 
"On avait un bouton "citer les corpus" mais il n'est plus disponible. J'ai vu qu'Alex François a mis la citation manuellement en fin de son corpus mwotlap sur son site web perso par ex. Est-ce qu'on ne devrait pas le générer automatiquement ? Cela pourrait-être fait pour le corpus entier : ex. nashta et pas juste les textes et phrases individuelles. "

**Comment by alexis-michaud** [comment]
Ca serait à ajouter dans la doc' : expliquer comment récupérer les infos de citation _via_ le DOI.
Dans Zotero par exemple, on peut importer automatiquement toutes les infos bibliographiques (la fiche entière de la référence), et la citer ensuite comme on ferait pour un article ou un livre) en utilisant le DOI.

**Comment by alexis-michaud** [comment]
Texte ajoutée à la page "[Outils](https://pangloss.cnrs.fr/outils?mode=pro#Comment%20citer%20une%20ressource,%20ou%20un%20corpus%20entier%20?)" : 

Comment citer une ressource, ou un corpus, dans une publication
La citabilité des ressources primaires est une problématique centrale pour la bonne intégration des dimensions complémentaires que sont les données, les outils et les publications. Pour les chercheuses et chercheurs, des références aux données établissent un lien précis, et fluidifie le trajet entre données et publications. En outre, le fait que les ressources soient citées revêt une importance certaine pour les personnes qui ont participé (à divers titres) à leur constitution. Cela constitue une reconnaissance de la part qu'ils ont dans l'entreprise de documentation des langues, et dans les progrès de la recherche scientifique qui s'appuie sur ces ressources.

Un des avantages des identifiants DOI déployés pour tous les documents de la collection Pangloss est qu'ils permettent d'importer les métadonnées (la fiche du catalogue du document concerné) dans un outil de gestion des données bibliographiques, tel que Zotero. Grâce à la fonction "Ajouter un document par son identifiant", il suffit de fournir un DOI pour importer dans Zotero une fiche complète pour la ressource en question.

Copie d'écran : import Zotero

Les métadonnées associées aux DOI ne sont pas au même format que les métadonnées OLAC (Open Language Archive Commmunity) du catalogue de la collection Pangloss (et plus généralement de la plate-forme Cocoon), qui font référence. Dans le détail, certains choix faits dans les équivalences entre métadonnées OLAC et métadonnées associées aux DOI sont contestables : du fait que tous les rôles définis dans les référentiels OLAC n'existent pas dans les métadonnées DOI, se trouvent identifiés comme "collaborateurs" des personnes ayant rempli des rôles assez divers. Mais l'export via les DOI a l'avantage de permettre de citer commodément les ressources comme on le ferait pour une publication scientifique.

À l'échelle d'un jeu de données entier (ce qui est désigné sur la présente interface comme un "corpus" : l'ensemble des documents disponibles dans un même parler), il n'existe pas actuellement de métadonnées toutes faites. Pour citer un corpus entier, dans une feuille de style prévue pour les publications scientifiques, notre recommandation est de fournir pour titre "Corpus nom de la langue", pour auteur le nom des chercheuses et chercheurs ayant constitué les ressources en question, et pour nom de publication "collection Pangloss (plate-forme Cocoon)".
