### ISSUE TITLE
Afficher les pdf avec le lecteur

### ISSUE THREAD

**Issue by sguillaume** [CNRS/Pangloss#147]
Lorsque le fichier d'annotation est un pdf, le lecteur ne l'affiche a priori pas (ça tourne dans le vide et il ne se passe rien).
Exemple avec cette ressource :https://pangloss.cnrs.fr/ (...) /corpus/show?oai_primary=cocoon-0c4bfc27-568d-370a-825b-e0009317affa&oai_secondary=cocoon-82f1a5e1-3ed6-33d2-be0e-115f030aeffc

**Comment by alexis-michaud** [comment]
@EdouardSombie : ticket renvoyé vers le dépôt 'Pangloss' depuis le dépôt 'Eastling' : il semble que ce soit une question d'intégration.
