### ISSUE TITLE
Bug affichage chercheur dans la case locuteur ?

### ISSUE THREAD

**Issue by sguillaume** [CNRS/Pangloss#152]
On dirait que le nom du chercheur s'insère à la place du locuteur quand aucun locuteur n'est indiqué.

ex : 
Sur la page corpus tout est ok il n'y a pas de locuteur : https://tmps04.huma-num.fr/corpus/Romani%20(Xoraxane,%20Southern%20Vlax,%20Greece)

Mais sur la page de la ressource le chercheur est indiqué comme locuteur : https://tmps04.huma-num.fr/corpus/show?lang=fr&oai_primary=cocoon-b48c740d-59ad-3d91-9956-fdd3ea003ba0&oai_secondary=cocoon-1330a853-7d11-346b-97c2-cd52ec8b0231

Dans la base de données pour la ressource en question (cocoon-b48c740d-59ad-3d91-9956-fdd3ea003ba0&oai_secondary) il n'y a pas de locuteur indiqué dans le champ contributors : 

{"depositor": [{"lang": "", "name": "Adamou, Evangelia"}],
  "researcher": [{"lang": "", "name": "Adamou, Evangelia"}]}

**Comment by alexis-michaud** [comment]
Bien vu ! 
![image](https://user-images.githubusercontent.com/6072524/103869685-f3460400-50ca-11eb-9592-550c6f405fed.png)
Pareil en mode PRO : 
![image](https://user-images.githubusercontent.com/6072524/103869635-e32e2480-50ca-11eb-9a93-77a1ed598726.png)
(ici [le DOI du document](https://doi.org/10.24397/pangloss-0000293))

**Comment by alexis-michaud** [comment]
Traité, ça marche. Quand il n'y a pas de locuteur indiqué, la boîte ne s'affiche pas.
