### ISSUE TITLE
Bug affichage locuteur quand "singer"

### ISSUE THREAD

**Issue by sguillaume** [CNRS/Pangloss#153]
Quand le locuteur est indiqué en tant que "singer" il n'a pas l'air de s'afficher dans la page corpus.

ex : "Chant de Kautjajuk aux chiens"
 https://tmps04.huma-num.fr/corpus/Inuktitut?lang=&mode= 

Par contre il apparait bien dans la page de la ressource : https://tmps04.huma-num.fr/corpus/show?oai_primary=cocoon-716275ae-cc61-4b1f-add7-322dee5a5ea5&lang=&mode=

Pour la ressource du dessus, la même locutrice est indiquée comme "speaker" et là elle apparait bien sur les 2 pages ("Histoire de Kautjajuk")

**Comment by alexis-michaud** [comment]
Bien vu ! 

Un élément de contexte @EdouardSombie : la personne qui parle (locutrice/locuteur) est décrite comme 'chanteuse/chanteur' (_singer_) pour la voix chantée. 

Il faut donc récupérer l'info "locuteur" (au sens large : la personne qu'on entend sur l'enregistrement / les personnes) dans plusieurs champs potentiels : chanteur, locuteur... 
(@sguillaume il y a quoi d'autre comme autres rôles dans le vocabulaire OLAC qu'il faut faire apparaître sur l'interface v2 sous la rubrique "locuteur" ?)

**Comment by sguillaume** [comment]
Il y a comme type de role pour les locuteurs : 
- speaker
- singer
- interpreter
- performer
- signer

**Comment by EdouardSombie** [comment]
Réglé
