### ISSUE TITLE
Bug téléchargement ressources secondaires

### ISSUE THREAD

**Issue by sguillaume** [CNRS/Pangloss#154]
Lorsque l'on consulte une page de ressource, si celle ci a une annotation (ressource secondaire associée) le téléchargement de la ressource secondaire se lance automatiquement (pdf, xml etc etc)

ex : https://tmps04.huma-num.fr/corpus/show?lang=&mode=&oai_primary=cocoon-b48c740d-59ad-3d91-9956-fdd3ea003ba0&oai_secondary=cocoon-1330a853-7d11-346b-97c2-cd52ec8b0231

**Comment by alexis-michaud** [comment]
Bien vu ! 
C'est depuis une màj récente du lecteur (aujourd'hui sans doute) que le téléchargement du fichier XML d'annotation est lancé automatiquement. "Effet spécial" non souhaité :)

Interaction entre le lecteur et les scripts du site de consultation ?

Je pense que ça concerne le lecteur. @m8nli9ht c'est sans doute pour toi ?

**Comment by alexis-michaud** [comment]
S'il est confirmé que ça concerne le lecteur, le ticket peut être transféré vers le dépôt Eastlingplayer. (Cliquer _"Transfer issue"_ dans le coin en bas à droite)

**Comment by m8nli9ht** [comment]
A priori ça ne vient pas du lecteur, pour rappel le lecteur ne gère pas le
multiannotations, c'est côté site pangloss que la surcouche "choix de
l'annotation " est proposée. Aussi, dans aucun cas le lecteur ne propose de
téléchargement (voir en exécutant sur eastling.huma-num.com)

Le ven. 8 janv. 2021 à 20:53, Alexis Michaud <notifications@github.com> a
écrit :

**Comment by alexis-michaud** [comment]
OK entendu ! Merci
@sguillaume avait bien vu ! Mes excuses pour le contretemps.
La balle passe dans le camp de @EdouardSombie

**Comment by EdouardSombie** [comment]
Salut, je viens d'envoyer un mail à ce sujet.
A priori, cela vient du player.
J'ai tester la page sans le player et le souci disparait...

**Comment by EdouardSombie** [comment]
Non, correction...
Je ne pense plus que le player soit en cause, mais plutôt une histoire d'accès à l'annotation...
Je regarde ça...

**Comment by EdouardSombie** [comment]
Re-salut,
Et bien, si... après vérification, le souci semble bien venir du player.
J'ai enlever toute ref à la ressource secondaire dans ma page et le téléchargemet se fait toujours.
En inspectant le document j'ai vu qu'il est fait référence à l'annotation dans le player, cf capture :

![Capture d’écran 2021-01-09 à 08 48 26](https://user-images.githubusercontent.com/66474742/104086383-c115dd00-5257-11eb-9a42-ba316701f262.png)

A mon avis, le problème vient du fait qu'on avait demandé à huma-num de changer les entêtes des documents pour qu'on puisse les télécharger directement à partir du site.

**Comment by m8nli9ht** [comment]
Salut Édouard,

Merci pour le détail qui confirme que cela vient du player, ce code
concerne les modifications pour le problème d'affichage du pdf. Par contre
il ne devrait pas s'afficher pour un XML...
Je corrige aujourd'hui et je vous tiens au jus.

Matthew

Le sam. 9 janv. 2021 à 08:57, EdouardSombie <notifications@github.com> a
écrit :

**Comment by EdouardSombie** [comment]
👍

**Comment by m8nli9ht** [comment]
Je viens de traiter et livrer, pouvez-vous retester ?

**Comment by alexis-michaud** [comment]
Bravo pour la bonne coordination (en plein week-end) 👍 
C'est bon, bogue résolu !
