### ISSUE TITLE
Annotations PDF non affichées

### ISSUE THREAD

**Issue by m8nli9ht** [CNRS/Pangloss#155]
https://eastling.huma-num.fr/player/?oai_primary=cocoon-ac836d96-0d5c-365a-9b60-8ee932e51413&oai_secondary=cocoon-a8698269-eb64-3219-9458-6da3162cefb6&lang=fr

**Comment by alexis-michaud** [comment]
(Sur [Eastling](https://eastling.huma-num.fr/player/?oai_primary=cocoon-ac836d96-0d5c-365a-9b60-8ee932e51413&oai_secondary=cocoon-a8698269-eb64-3219-9458-6da3162cefb6&lang=fr&mode=normal), ça marche à merveille pour moi)
