### ISSUE TITLE
Problème marge selon taille écran

### ISSUE THREAD

**Issue by sguillaume** [CNRS/Pangloss#157]
Il y a des tailles d'écran (de fenêtres) ou il manque de la marge.
La marge est de plus en plus grande quand on agrandit la fenêtre et d'un coup elle devient trop petite.
Est ce que l'on peut modifier ça ?

<img width="1275" alt="Manque_marge" src="https://user-images.githubusercontent.com/6065936/104237969-284eaf80-5459-11eb-9710-52d82f53d977.png">

**Comment by EdouardSombie** [comment]
C'est réglé :)
