### ISSUE TITLE
Petits points oranges bizarres

### ISSUE THREAD

**Issue by sguillaume** [CNRS/Pangloss#158]
Il y a des petits points oranges étranges à droite du DOI des phrases.
Peut on les retirer ?

![Points_oranges](https://user-images.githubusercontent.com/6065936/104238715-af9c2300-5459-11eb-8990-ddc8f9903e32.png)

**Comment by alexis-michaud** [comment]
Ce sont les bordures du tableau prévu pour le mot à mot (FORM et TRANSL au niveau W, au niveau M), n'est-ce pas ?
Il faudrait introduire une condition : si un tableau est vide, ne pas lui mettre de bordures ?

**Comment by EdouardSombie** [comment]
C'est réglé
