### ISSUE TITLE
Affichage titre et description en l'absence d'attribut langue (fr / en)

### ISSUE THREAD

**Issue by sguillaume** [CNRS/Pangloss#159]
Le kakabé, langue pour laquelle quasiment toutes les ressources ont un titre et une description, n'a aucun titre ni description qui s'affiche sur le site.

https://pangloss.cnrs.fr/corpus/Kakabe?lang=fr&mode=pro

La langue des titres et des descriptions n'est pas indiquée dans la BDD.
Le problème ne vient surement pas de là car de nombreuses autres ressources doivent se trouver dans ce cas là aussi.
(Si jamais c'est ça, il faudrait afficher par défaut ce titre unique dans la version anglaise et française du site).

**Comment by EdouardSombie** [comment]
Réglé.
Si pas de titre ou description disponible en "fr" ou "en" : récupère la valeur du titre "sans langue"

**Comment by alexis-michaud** [comment]
Ca marche !! 

A étendre aussi à la liste des ressources sur la page du corpus.

**Comment by alexis-michaud** [comment]
C'est tout bon :smiley:
![image](https://user-images.githubusercontent.com/6072524/106353292-c52e9b00-62e9-11eb-83e0-4cdcd8343efa.png)
