### ISSUE TITLE
Affichage des métadonnées intégrales

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/Pangloss#16]
Dans la nouvelle interface ça serait bien de rétablir l'icône "Informations" dans la liste de ressources, non? et aussi sur la page où s'affiche une ressource.
Là il y a qq métadonnées simplifiées mais pas la totalité. En particulier, les identifiants ark, oai...

**Comment by sguillaume** [comment]
Les métadonnées sont aujourd'hui disponibles dans leur intégralité au format XML !
Pour chaque ressource dans "A propos de la ressource" puis "Téléchargements" on peut télécharger non seulement les fichiers audio et d'annotations mais aussi les fichiers de métadonnées qui décrivent ces ressources !

**Comment by alexis-michaud** [comment]
👍 
![image](https://user-images.githubusercontent.com/6072524/58434318-5aac6d00-80bb-11e9-8bf4-0be1d6d2c656.png)
