### ISSUE TITLE
mentions légales en mode PRO

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/Pangloss#162]
L'interface de saisie pour les mentions légales ne comporte que deux champs : fr et en, et c'est très bien ainsi.

Mais pour l'affichage, il faut afficher le contenu français ici aussi
https://pangloss.cnrs.fr/mentions-l%C3%A9gales?mode=pro

et le contenu anglais ici aussi
https://pangloss.cnrs.fr/mentions-l%C3%A9gales?mode=pro&lang=en

Pour l'instant le contenu fait défaut.

![image](https://user-images.githubusercontent.com/6072524/104747915-6269cb00-5751-11eb-820c-d954db85a097.png)

**Comment by EdouardSombie** [comment]
Réglé !
