### ISSUE TITLE
carte des langues pas visible sur iPad ni Android

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/Pangloss#165]
Sur Android : la mention "Carte des corpus" apparaît (page d'accueil, et page "Corpus") mais la carte n'apparaît pas.

![image](https://user-images.githubusercontent.com/6072524/106514796-020ab580-64d5-11eb-80d3-fb2d9cfff051.png)

D'après un retour utilisateur : c'est pareil sur iPad.

**Comment by EdouardSombie** [comment]
C'est fait exprès !!
La carte serait inutilisable sur un téléphone...

Par contre, elle s'affiche sans souci sur un ipad en mode paysage :)

**Comment by alexis-michaud** [comment]
Ah, mais dans ce cas, est-ce qu'il ne faudrait pas retirer la mention "Carte des corpus" quand la carte n'est pas affichée ? 
Quand il y a marqué "Carte des corpus" mais qu'il n'y a pas de carte affichée, difficile de deviner que c'est pas un bogue :smiley:

**Comment by EdouardSombie** [comment]
Je me dis que ce serait peut-être mieux de mettre un message du type :
[Cette carte n'est pas disponible sur terminal mobile]

Qu'en dis-tu ?
Cela incitera à consulter sur un plus grand écran.

**Comment by alexis-michaud** [comment]
Excellente idée : 
- les habitués du site n'ont pas à ré-apprendre un mode 'mobile' trop différent : l'interface se reconnaît bien, "on est chez soi", et quand il y a une différence, elle est expliquée
- les visiteurs qui jettent un premier coup d'oeil ont le message important selon lequel c'est conçu pour affichage sur un terminal type tablette (au moins), pas un ordiphone. 

Bref, moi je suis tout pour, personnellement.
Après, pour la formulation, à voir pour ne pas prêter au malentendu selon lequel ça serait une question de bande passante ou navigateur, par exemple. C'est simplement une affaire de taille d'écran.  
[Carte non disponible pour taille d'écran inférieure à...] ?
[Carte non disponible pour cette taille d'écran] ?

@sguillaume pourrait avoir des idées ? C'est elle qui a eu le retour utilisateur

**Comment by sguillaume** [comment]
Vous êtes sûrs qu'on ne peut pas afficher la carte sur mobile ?
Les gens peuvent tourner leur tel pour avoir un mode paysage et donc plus large.
Et j'ai souvenir que l'ancienne carte du site était affichée sur mobile et que ça passait.
On peut zoomer en agrandissant avec les doigts. les gens sont habitués à ça normalement.

**Comment by EdouardSombie** [comment]
Très honnêtement, je pense que la carte ne sera très facile d'usage sur mobile.
Mais étant donné que Séverine semble y tenir, j'ai fait en sorte qu'elle s'affiche (le mieux possible) sur téléphone.

**Comment by alexis-michaud** [comment]
Maintenant que je vois le résultat je pense que @sguillaume a bien fait d'insister. Sur petit ordiphone, ça passe très bien, et le fait d'avoir une carte me paraît très incitatif.
