### ISSUE TITLE
Faire apparaitre EGG dans la liste des ressources secondaires

### ISSUE THREAD

**Issue by sguillaume** [CNRS/Pangloss#167]
Ca serait bien de faire apparaitre un logo EGG (comme le logo XML) dans la liste des ressources secondaires quand il y a un EGG.
Ex : Corpus yongning na

"how the lake was created (version 4)" a un EGG mais seul le XML apparait dans la liste des ressources.

On commence à avoir beaucoup d'EGG et c'est dommage qu'ils ne soient visibles que lorsque l'on consulte directement une ressource (https://doi.org/10.24397/pangloss-0004661).

**Comment by alexis-michaud** [comment]
Oui, le logo de l'EGG n'apparaît pas lorsqu'on a la liste des ressources d'un corpus et qu'il y a un EGG de disponible.
Ex [ici](https://pangloss.cnrs.fr/corpus/Yongning%20Na?lang=en&mode=pro) (corpus na, où il y a plein d'EGG). La ressource "How the Lake was created (version 4)" a un son, un xml et un EGG mais seul le son et le xml sont visibles.

**Comment by EdouardSombie** [comment]
Fait !

**Comment by sguillaume** [comment]
Merci ! :)
