### ISSUE TITLE
Affichage de toutes les ressources secondaires

### ISSUE THREAD

**Issue by sguillaume** [CNRS/Pangloss#170]
Ca serait bien de pouvoir avoir accès à la même page (avec les mêmes options d'affichage) quelle que soit la ressource secondaire à laquelle on veut accéder.

Je m'explique.
Chaque ressource secondaire est liée à une ressource primaire.
Il faudrait que l'url qui affiche ces ressources https://pangloss.cnrs.fr/corpus/show?&oai_primary=OAI_PRIMAIRE&oai_secondary=OAI_SECONDAIRE
ramène sur la même page quel que soit l'OAI_SECONDAIRE que l'on souhaite afficher et qui est lié à l'OAI_PRIMAIRE.

Ca marche quand la ressource secondaire est une ressource "affichable" telle que annotations xml ou pdf mais ça ne marche pas avec les EGG.
Il faudrait que les url avec oai d'un EGG ouvre aussi la même page avec le son (et les annotations s'ils y en a).

ex: avec l'OAI_PRIMAIRE = cocoon-ecaff366-c3d1-341b-b725-78bfbc7bc7e2
Cette ressource primaire a :
- une annotations XML (OAI_SECONDAIRE = cocoon-b8f0c77a-b602-335c-9c7b-0dddc656706f)
- un fichier EGG (OAI_SECONDAIRE = cocoon-22cf60f0-3b08-4cb6-8f60-f03b08acb61a)

Ca donnerait la même page quelle que soit l'une de ces 3 urls:

(son uniquement) -> https://pangloss.cnrs.fr/corpus/show?oai_primary=cocoon-ecaff366-c3d1-341b-b725-78bfbc7bc7e2

(son et annotation) -> https://pangloss.cnrs.fr/corpus/show?oai_primary=cocoon-ecaff366-c3d1-341b-b725-78bfbc7bc7e2&oai_secondary=cocoon-b8f0c77a-b602-335c-9c7b-0dddc656706f

(son et EGG) -> https://pangloss.cnrs.fr/corpus/show?oai_primary=cocoon-ecaff366-c3d1-341b-b725-78bfbc7bc7e2&oai_secondary=cocoon-22cf60f0-3b08-4cb6-8f60-f03b08acb61a

Le problème est quand on utilise le DOI d'un EGG. Ca renvoit à une url du type oai_primaire = oai du son et oai_secondaire = oai de l'EGG
Et là ça ouvre une page où même s'il y a des annotations liées au même son, elle n'apparaissent pas. Seul le son apparait. Ce qui est dommage.

**Comment by EdouardSombie** [comment]
Pour répondre à la demande de Séverine : "Ca serait bien de pouvoir avoir accès à la même page (avec les mêmes options d'affichage) quelle que soit la ressource secondaire à laquelle on veut accéder." : 
Ce n'est pas possible car le player récupère l'OAI de la ressource secondaire dans l'URL de la page.
Toutefois, je vais faire en sorte de vérifier la nature de la ressource secondaire demandée dans l'URL : si c'est un egg, réécriture de la page pour afficher la ressource avec la première annotation disponible.

**Comment by EdouardSombie** [comment]
C'est fait !
Si l'url demande une ressource secondaire de type egg ou jpg, l'url est modifiée pour afficher la première ressource secondaire 'affichable'.
En vérifiant avec l'exemple donné par Séverine, je vois que le karaoké ne fonctionne pas parfaitement : le mot qui est lu n'est pas mis en avant et semble se caler en bas de la fenêtre... C'est normal ?

https://pangloss.cnrs.fr/corpus/show?oai_primary=cocoon-ecaff366-c3d1-341b-b725-78bfbc7bc7e2&oai_secondary=cocoon-22cf60f0-3b08-4cb6-8f60-f03b08acb61a

**Comment by sguillaume** [comment]
Merci c'est top comme ça !

Oui Matthew a aussi vu ce décalage de lecture pour les listes de mots et il va corriger le truc rapidement.
