### ISSUE TITLE
Indiquer les mots d'emprunts

### ISSUE THREAD

**Issue by sguillaume** [CNRS/Pangloss#172]
Dans les annotations il y a la possibilité d'indiquer les mots d'emprunt.
Il avait été décidé de les mettre en italique (lors d'un projet ANR).

Ces mots ou morphèmes sont détectables par leur classe nommée "CL" : 
Par exemple : `<M class="CL">`

Il faudrait, dans cette nouvelle interface, qu'ils apparaissent aussi en italique.
C'est faisable facilement ?

Voici un exemple de texte où il y a des mots d'emprunt : 
https://pangloss.cnrs.fr/corpus/show?lang=fr&mode=pro&oai_primary=cocoon-a1adb34c-c1c2-3bc0-a0e3-b9df97c6f155&oai_secondary=cocoon-6beaee6a-42b8-3820-8180-0e9a626ec5de

**Comment by alexis-michaud** [comment]
@EdouardSombie 
Indication de Matthew : 

> "Une classe "CL" a été créée pour les morphèmes, il faut lui attribuer une instruction CSS pour que la police soit en italique"

**Comment by EdouardSombie** [comment]
C'est fait !

**Comment by sguillaume** [comment]
J'ai un problème d'affichage. Plus aucune annotation ne s'affiche (et un pb de taille du logo DOI).

ex : 
![Uploading pb.png…]()

**Comment by EdouardSombie** [comment]
Salut Séverine, il faut vider ton cache navigateur.

**Comment by sguillaume** [comment]
Super les mots d'emprunts en italiques !

Merci :)

**Comment by EdouardSombie** [comment]
👍
