### ISSUE TITLE
alignement à revoir pour gloses interlinéaires : confusion entre lignes

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/Pangloss#202]
Document : 
corpus/show?mode=pro&oai_primary=cocoon-16586ac3-6bba-3c3f-86d9-0b9f877c605a&oai_secondary=cocoon-ec43abba-bd90-3970-a9a3-1f69ddbd75c0&optionWords=true&optionNotes=true&optionTranscriptions=%2Bphone&optionTranslations=%2Bcn%2Bfr&optionGlosses=%2Bcn%2Bfr%2Ben&optionWholeTranscriptions=false&optionWholeTranslations=%2Bcn

L'unité /mi˧-ʝi˩-tsɤ˧˥/, encodée comme un mot (\<W\>), se trouve répartie sur 2 lignes non successives : 
/mi˧-ʝi˩/ se retrouve sur la ligne des gloses (celle qui commence par 'grand'père')

![image](https://user-images.githubusercontent.com/6072524/96410530-5bc9c700-11e7-11eb-9348-24334fc8282a.png)

Voici l'affichage "ancien", qui est correct :
![image](https://user-images.githubusercontent.com/6072524/96410240-e5c56000-11e6-11eb-8b38-fc772c7cd28f.png)

**Comment by alexis-michaud** [comment]
@EdouardSombie la balle passe donc dans ton camp ! À toi de jouer :)

**Comment by EdouardSombie** [comment]
Je m'en occupe !

**Comment by EdouardSombie** [comment]
Re-salut
C'est fait !
J'en ai profité pour améliorer l'affichage des mots au survol (le reste de la page ne bouge plus).
A bientôt
<img width="813" alt="Capture d’écran 2023-01-16 à 15 23 04" src="https://user-images.githubusercontent.com/66474742/212700356-c9f53654-25a0-498f-924d-802b7b193f53.png">
