### ISSUE TITLE
Balise title dans l'en-tête:  générique ou spécifique ?

### ISSUE THREAD

**Issue by Tavalmayam** [CNRS/Pangloss#37]
Quand je poste un texte Pangloss sur Facebook ou ailleurs, le titre qui apparaît est trop impersonnel (toujours le même titre générique quelle que soit la ressource):
`Collection Pangloss - Ressource`
Celui-ci correspond à la balise `title` dans l'en-tête du Html
`<title>Collection Pangloss - Ressource</title>`
(celle-ci se reflète également dans l'intitulé de l'onglet dans firefox, par exemple)
Serait-il possible que le titre de la page représente le contenu? (titre du texte, langue). [Par exemple](http://lacito.vjf.cnrs.fr/pangloss/corpus/show_text.php?id=crdo-MLV_AF0101160_SOUND&idref=crdo-MLV_AF0101160), 
`Collection Pangloss – L’homme Cordyline (mwotlap)`
ou plus brièvement:
`Pangloss – L’homme Cordyline (mwotlap)`

Cela pourrait être possible, grâce au Php?

Peut-être faudra-t-il être attentif à la langue:  si on a le choix entre titre anglais ou français, logiquement ceci correspondrait au choix de l'interface (angl/fr).
Merci

**Comment by alexis-michaud** [comment]
Fait pour la version 2 du site Pangloss
et en cours d'affinement : voir #114
