### ISSUE TITLE
Cases à cocher/décocher dans l'interface : bouton "Word" inerte ?

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/Pangloss#43]
Le 1er septembre, l'interface a été améliorée (merci @sguillaume) pour que l'affichage des gloses dans différentes langues (au niveau du mot/morphème) puisse être coché/décoché. Ainsi, pour les textes pumi traduits en chinois et en anglais, on peut choisir chinois, ou anglais, ou les deux (qui s'affichent alors sur des lignes séparées). 

C'est une amélioration très bienvenue, surtout dans la perspective d'un enrichissement progressif des ressources.

Dans Chrome, le bouton/ boîte à cocher "Words" est inerte. La ligne des gloses par morphème (transcription) s'affiche (ce qui est bien) mais en décochant ça ne la fait pas disparaître.

(Dans Firefox j'ai des soucis mais c'est sans doute lié à mon installation de Firefox, qui est pourtant à jour mais a un comportement erratique.)

**Comment by alexis-michaud** [comment]
Nouveau problème, du même ordre.

C'est toujours dans CHROME, et sur mon ordinateur portable (qui a déjà eu des soucis d'affichage par le passé).  
Cette fois-ci, c'est en décochant la transcription par phrase ou la traduction par phrase que ça coince (il ne se passe rien et la case ne se décoche pas). 

Par contre l'affichage des gloses au niveau du mot (cocher/décocher) fonctionne bien.

Exemple : 

![image](https://user-images.githubusercontent.com/6072524/60420625-750cc580-9be8-11e9-9eff-7ed961d41b22.png)

Pour [ce document-ci](https://doi.org/10.24397/pangloss-0002290).

**Comment by sguillaume** [comment]
Réparé !

**Comment by alexis-michaud** [comment]
👍
