### ISSUE TITLE
Licences et copyrights

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/Pangloss#46]
Pour les questions de licences et copyrights, il nous faut proposer aux déposants des solutions qui soient simples et claires, tout en étant assez diverses pour couvrir des situations très différentes d'un pays à l'autre, d'un lieu à l'autre, d'un type de document à l'autre. 

# Licences pour les outils logiciels:

A l'heure actuelle, le CNRS ni nos laboratoires de rattachement n'ont de politique de licence très précise. La tendance générale est à la mise à disposition en libre accès des résultats de la recherche publique. Pour "nos" outils, le choix nous revient. 

Gilles Degottex, qui maintient le repositoire [COVAREP](https://github.com/covarep/covarep), conseille de choisir entre les 3 solutions suivantes, des plus flexibles aux plus contraignantes: 

> A) Une licence comme BSD ou MIT, qui permet à l'utilisateur de faire tout ce qu'il veux avec le code. Par example, modifier le code sans rendre ses modifications publiques, puis inclure ce code dans un logiciel qui n'est pas open-source.

> B) Licence LGPL: Toute modification du code doit être rendue publique. Par contre, c'est encore possible d'inclure ce code (modifié ou non) dans un logiciel dont le code n'est pas open-source (ex. le code de l'estimation d'Oq est open-source, mais le code de l'interface utilisateur ne l'est pas).

> C) Licence GPL: Toute modification du code doit être rendue publique. De plus, tout logiciel qui utilise ce code doit être open-source.

> Dans un cadre de recherche, nous encourageons à forcer l'utilisateur a rendre les modifications publiques (et donc les potentielles améliorations). Ce qui restreindrait le choix entre (B) et (C). Ensuite, nous conseillons la license LGPL (choix B), de façon à être "industry-friendly", en laissant la porte ouverte aux éventuelles commercialisations et donc à de potentiels partenariats.

Que diriez-vous d'utiliser une licence LGPL pour les outils du projet, et plus généralement les outils de Pangloss/CoCoON?

# Licences pour les ressources: enregistrements, annotations, dictionnaires...

Trois licences sont proposées pour Pangloss/CoCoON:

Licence CreativeCommons BY-NC
Autorisation de :
* Diffusion de la ressource
* Modification de la ressource
Obligation de :
* Utilisation à des fins non commerciales
* Citation de l'auteur

Licence CreativeCommons BY-NC-SA
Autorisation de :
* Diffusion de la ressource
* Modification de la ressource
Obligation de :
* Utilisation à des fins non commerciales
* Citation de l'auteur
* Diffusion de la ressource modifiée avec la même licence

Licence CreativeCommons BY-NC-ND
Autorisation de :
* Diffusion de la ressource
Obligation de :
* Utilisation à des fins non commerciales
* Citation de l'auteur 

Moi je pense avoir systématiquement choisi BY-NC-SA. Que diriez-vous d'en faire la valeur par défaut? Après libre à chacun d'en utiliser une autre, mais ça épargnerait à chacun des déposants de passer du temps à se poser ces questions si on n'y porte pas d'intérêt particulier. De toute façon, à part qq cas extrêmes où ça finit devant les tribunaux, tout repose sur la bonne foi et la bonne volonté des gens: les plagiaires, faussaires et autres savent très bien ce qu'ils font et enfreignent les règles en connaissance de cause. Il faut juste souhaiter que ça ne nous arrive pas... ou du moins que les bénéfices de la mise en ligne dépassent ses inconvénients, ce dont pour ma part je suis pleinement convaincu.

**Comment by alexis-michaud** [comment]
Pour info, quelques réflexions (qui n'engagent que moi) sont exposées [ici](https://github.com/alexis-michaud/pangloss/tree/master/licences).

**Comment by alexis-michaud** [comment]
En direct de la Journée d'étude ["Questions éthiques & cadre juridique autour des corpus langagiers"](https://corli.huma-num.fr/journee-questions-ethiques2019) : le souhait d'avoir des solutions aux principales questions est (bien sûr) partagé.

**Comment by alexis-michaud** [comment]
Mentions légales prêtes. 
Reçu le certificat attestant de l'inscription au registre du traitement de données à caractère personnel.
Choix de licence pour les outils : peut varier en fonction des partenaires. Par exemple pour [Elpis](https://github.com/CoEDL/elpis) (transcription automatique), la licence choisie est Apache-2.0.

**Comment by EdouardSombie** [comment]
Il faudrait ajouter cela à la page mentions légales :

SVG icons "Right", "Speaker", "Film", "XML File", "TXT File", "JPG File", "Map pin", "Plus", "Minus", "Magnifying Glass" and "Download" by Hea Poh Lin, from thenounproject.com.

**Comment by alexis-michaud** [comment]
Fait ! Merci bcp
