### ISSUE TITLE
dépôt texte na "MUSHROOMS" (champignons)

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/Pangloss#65]
Bonjour Séverine, 

Je m'aperçois que le texte na crdo-NRU_F4_MUSHROOMS.xml n'a pas été mis en ligne. Bizarre bizarre : il est fini depuis 2 ans, et il figure dans le répertoire qui contient les 27 fichiers na (XML) dont tu effectues la mise à jour dans Pangloss/Cocoon de temps à autres. Bon en tout cas mieux vaut tard que jamais, il faudrait le verser à l'archive. 

Les métadonnées sont les mêmes que pour [le fichier audio, déjà en ligne](http://www.language-archives.org/item/oai:crdo.vjf.cnrs.fr:crdo-NRU_F4_MUSHROOMS_SOUND).

Le XML est [ici](https://github.com/alexis-michaud/na/blob/master/TEXT/F4/crdo-NRU_F4_MUSHROOMS.xml), dans le réservoir GitHub (public) créé pour le na.

(Pour les prochaines mises à jour, c'est là qu'il faudra récupérer les fichiers, et plus dans 'HimalCo'; mais c'est un autre sujet !)

Merci bcp

**Comment by sguillaume** [comment]
Fait

**Comment by alexis-michaud** [comment]
👍
