### ISSUE TITLE
[DOREMIFA] ouverture au public des données hung de Michel Ferlus (dialectes: toum, lyha, tày poọng, phong)

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/Pangloss#75]
Jusqu'ici, la consigne fournie par Michel Ferlus pour ces données était : 

> L'usage des ressources du corpus hung est provisoirement réservé par leur auteur (Michel Ferlus). Pour demander l'accès à ces données, merci de bien vouloir prendre contact avec l'auteur.

L'autorisation de mise en ligne (licence CC, comme à l'ordinaire) a maintenant été donnée :-)

(détails : courriel du 30 décembre 2018)

**Comment by alexis-michaud** [comment]
Précisions pour le dépôt : toutes ces langues ont pour code ISO **HNU**

17 fichiers en tout

4 langues

Le transfert est fait : les fichiers sont dans le dossier DOREMIFA de la baie du LACITO.

**Comment by alexis-michaud** [comment]
Les 4 pages HTML statiques sont dans le dossier "Langues"

( GitHub\Pangloss\Pangloss_Website\languages )

**Comment by sguillaume** [comment]
Fait !

**Comment by alexis-michaud** [comment]
👍
