### ISSUE TITLE
[DOREMIFA] dépôt nouveaux documents dans 2 langues : BRU et RMET

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/Pangloss#77]
Cf courriel du 31 décembre 2018, 17h45.

**Comment by sguillaume** [comment]
Fait !

**Comment by alexis-michaud** [comment]
👍 

Reste à mettre en ligne les pages _langue_ (2 langues concernées x 2 langues de description : fra+eng = 4 pages HTML). Elles sont dans le dossier : 

GitHub\Pangloss\Pangloss_Website\languages

**Comment by alexis-michaud** [comment]
(Ce sont les premiers documents dans ces langues.)

**Comment by alexis-michaud** [comment]
Pour la langue [RMET](https://lacito.vjf.cnrs.fr/pangloss/corpus/list_rsc.php?lg=Rmet&name=rmet), c'est en ligne, merci. Il faut en revanche corriger le pays: ça concerne le LAOS et non le VIETNAM.

Par contre, la langue BRU ne semble pas avoir été ajoutée dans la liste des langues. Les données et la page sont en ligne, on peut le voir en écrivant à la main une URL : [https://lacito.vjf.cnrs.fr/pangloss/corpus/list_rsc.php?lg=**Bru**&name=**bru**](https://lacito.vjf.cnrs.fr/pangloss/corpus/list_rsc.php?lg=Bru&name=bru)

Merci donc d'ajouter BRU dans la liste des langues, pour la page en anglais et en français. Le pays est : LAOS, pour ces deux langues. 

(La langue BRU apparaîtra de façon distincte de la langue MAKONG, qui fait partie du même ensemble dialectal. Ca, ce n'est pas grave, le lien pourra se faire par une référence et/ou une explication. Et pour la liste des langues, vu comment elle est organisée actuellement, c'est pas plus mal d'avoir 2 lignes séparées : ça permet d'indiquer que le MAKONG est parlé au Vietnam et le BRU au Laos.)

**Comment by sguillaume** [comment]
C'est fait

**Comment by alexis-michaud** [comment]
👍
