### ISSUE TITLE
site Pangloss : association langues - pages pour groupe péarique (mon-khmer)

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/Pangloss#78]
Il existe une page Pearic (fr : Pearic.php, en : Pearic_en.php) qui fournit les informations concernant les cinq langues suivantes : 

chong heup | chong lo | chong tratt | pear | samré

Dans l'interface ancienne, cette page servait de portail pour les 5 langues. Maintenant que chaque langue (dialecte) doit avoir sa page, ces 5 langues se retrouvent sans lien avec le document de présentation : aucune page ne s'affiche pour ces cinq langues. 

Dans un premier temps, il faut recopier la page d'origine (en mettant à jour les liens) et changer le nom du fichier de façon à ce que cette page s'affiche pour les 5 langues : elle contient les infos qui permettent au visiteur de se repérer.

Dans un 2e temps, les 5 pages désormais séparées pourront s'étoffer de nouveaux commentaires. Mais il reste utile d'avoir un 'tronc commun' concernant le péarique sur la page de chacune des langues, pour renvoyer entre parlers de ce groupe. (Pour info : 2 documents dans une 6e langue péarique pourront être déposés en 2019.)

**Comment by sguillaume** [comment]
Fait !

**Comment by alexis-michaud** [comment]
👍
