### ISSUE TITLE
mise à jour dossier DOI

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/Pangloss#79]
(rappel : les DOI, objet de #32, sont maintenant déployés)

Le code actuel date de 6 mois:

https://github.com/CNRS/Pangloss/tree/master/DOI_stage/DoiPangloss

Est-ce qu'il n'y a pas eu de modifications depuis ?

Le chemin aussi serait peut-être à changer, simplement DOI plutôt que DOI_stage ?

**Comment by vasaura** [comment]
En effet, ce code représente le travail réalisé pendant le stage. 
Nous avions besoin d'un repository dédié exclusivement au code de cette application DOI et de le détacher du reste des dossiers Pangloss.
Puisque je n'avais pas la main sur le repository CNRS, j'ai déployé la deuxième version du code ici https://github.com/vasaura/DoiPangloss. Cela nous a permis de travailler en collaboration avec @sguillaume sur le code en faisant de PR, merge, commit, etc.... 
De plus, il y a une troisième version du code réalisée par Séverine. Il me semble que cette version est encore en local. 
Il serait idéal de rendre compte de ces trois versions sans les écraser car elles ont apporté chacune un niveau supplémentaire de traitement. 
Je vous invite, toi ou Séverine, à faire un fork du https://github.com/vasaura/DoiPangloss et sur ce fork, ajouter la troisième version du code qui remplacera la deuxième.

**Comment by alexis-michaud** [comment]
> Il serait idéal de rendre compte de ces trois versions sans les écraser car elles ont apporté chacune un niveau supplémentaire de traitement.

Oui, la progression du projet est intéressante. GitHub permet justement de conserver l'historique : les nouvelles versions n'écrasent pas les précédentes, qui restent accessibles via [l'historique des mises à jour](https://github.com/CNRS/Pangloss/commits/master). Avoir trois dépôts différents pour les trois versions, ça ne serait pas dans l'esprit de GitHub, je pense, et ça serait malcommode à gérer.

Si je comprends bien, une manip' à effectuer, ce serait de mettre à jour le dépôt Pangloss en mettant en ligne la version 3 ("troisième version du code réalisée par Séverine"), que Séverine a encore fignolée la semaine passée, et qui reste la version à jour. Comme c'est du code qui a vocation à continuer à servir pour Pangloss, je serais d'avis qu'il soit hébergé sur le compte CNRS/Pangloss. 

[La version associée à ton compte GitHub](https://github.com/vasaura/DoiPangloss) resterait disponible à son adresse actuelle. Dans la page de présentation (README) tu pourrais fournir un lien vers la version en ligne dans Pangloss. En revanche, la création de branches serait réservée au scénario classique dans lequel, à l'avenir, quelqu'un d'autre que le développeur principal voudrait apporter des modifs au code. 

La balle est donc dans votre camp, @sguillaume @vasaura (ou est-ce que j'ai raté quelque chose ?)

Merci et à+

**Comment by alexis-michaud** [comment]
@vasaura Si le code est à jour et que cette demande n'est plus à l'ordre du jour, merci de fermer ce ticket

**Comment by vasaura** [comment]
Oui, Severine a fait le fork donc on peut fermer l’issue

**Comment by alexis-michaud** [comment]
Il faut donc supprimer le dossier qui est [ici](https://github.com/CNRS/Pangloss/tree/master/DOI_stage/DoiPangloss), non ?

**Comment by vasaura** [comment]
oui, mais il vaut vérifier avant auprès de @sguillaume

**Comment by vasaura** [comment]
MAJ
Je viens de réaliser qu'un fork a été réalisé directement sur le compte CNRS, donc il faut mieux citer celui-ci: https://github.com/CNRS/DoiPangloss.
@sguillaume pourra nous dire si c'est vraiment la dernière version et non pas celle que j'ai cité plus haut.

**Comment by alexis-michaud** [comment]
OK super. 

@sguillaume la balle est dans ton camp pour supprimer le sous-dossier dans le dépôt "Pangloss" : 

https://github.com/CNRS/Pangloss/tree/master/DOI_stage/DoiPangloss
