### ISSUE TITLE
affichage DOI : mettre PANGLOSS en minuscules ?

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/Pangloss#80]
(rappel : les DOI, objet de #32, sont maintenant déployés)

Actuellement, dans les DOI, 'Pangloss' s'affiche tout en majuscules

Dans la citation (bouton CITATION)
doi: 10.24397/**PANGLOSS**-0000001. 
https://doi.org/10.24397/PANGLOSS-0000001 (Accessed 2019-02-06).

Ou via le bouton "DOI"
https://doi.org/10.24397/PANGLOSS-0000001

Ca peut avoir des avantages, de faire figurer '**PANGLOSS**' en majuscules : ça différencie le nom de la collection, '**PANGLOSS**', de l'expression technique '**doi**', dont la casse la distingue. Mais la mode en ce moment c'est les minuscules plutôt que les manuscules, et comme l'intérêt des DOI eux-mêmes tient à un élément de mode (/prestige), ça se justifierait de céder à la mode et écrire en minuscules : 

https://doi.org/10.24397/pangloss-0000001
etc.

(éventuellement avec un P majuscule, s'il y a des adeptes ? https://doi.org/10.24397/Pangloss-0000001 La mode étant ce qu'elle est, le tout-minuscule paraîtrait une bonne solution... jusqu'à ce que la mode change!)

Techniquement il n'y a pas d'obstacle : avec ou sans majuscules, la résolution fonctionne bien.

**Comment by vasaura** [comment]
Je me souviens que j'ai eu ce souci même pendant la phase de test. Je me demandais si cela était dû à un fonctionnement par défaut de DataCite. Mais je ne sais plus. A creuser avec @sguillaume

**Comment by sguillaume** [comment]
C'est modifié en tout minuscules !
On récupère effectivement en majuscule ce qui est assez étrange car je ne crois pas que ça soit enregistré en majuscule.

**Comment by alexis-michaud** [comment]
👍
