### ISSUE TITLE
correction dans la liste des langues : pour le khmu, le pays est : LAOS et non VIETNAM

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/Pangloss#81]
Dans la liste des langues : pour le khmu, le pays à indiquer est : LAOS et non VIETNAM
![image](https://user-images.githubusercontent.com/6072524/55108693-689e3b80-50d4-11e9-8e8b-9b8753999a2c.png)

(Il y a aussi des Khmu au Vietnam, mais la majeure partie de la population est au Laos, et c'est là-bas que les enregistrements ont été réalisés.)

**Comment by sguillaume** [comment]
Fait !

**Comment by alexis-michaud** [comment]
👍
