### ISSUE TITLE
DataCite Metadata Schema 4.2 Update

### ISSUE THREAD

**Issue by vasaura** [CNRS/Pangloss#83]
@sguillaume 
Depuis quelques jours, il y a une nouvelle version de schéma de métadonnées pour les DOI: la version 4.2. 
Cela n'a pas d'impact immédiat sur les métadonnées de Pangloss, mais il vaut mieux mettre à jour la mention du schéma dans l'application. 
Donc, il faut remplacer dans DoiPangloss/objects/Record.py (ligne 137) "http://schema.datacite.org/meta/kernel-4.1/metadata.xsd" par "http://schema.datacite.org/meta/kernel-4.2/metadata.xsd"
et pareil dans DoiPangloss/objects/Phrase.py (ligne48)
(à tester avec un doi de test avant de lancer sur toute la base)

Les métadonnées des versions 2.1 et 2.2 du schéma ne sont plus acceptées, donc elles doivent être mises à jour. Heureusement ce n'est pas le cas de Pangloss (pas encore, mais c'est à surveiller dans le temps) 
Amitiés

**Comment by sguillaume** [comment]
C'est bon pour le changement dans le script.
J'ai fait un commit dans master. c'est bon pour toi ?
Tout a l'air ok mais je n'ai pas relancé sur la base pour l'instant.
Merci !
