### ISSUE TITLE
Changement du chemin pour le dossier DOI ?

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/Pangloss#84]
Pour l'instant, il semble que le dossier DOI traverse un dossier vide (ou supprimé), "DOI_stage": 

https://github.com/CNRS/Pangloss/tree/master/DOI_stage/DoiPangloss

Ne faudrait-il pas réorganiser de façon à ce que "DOI" soit directement dans la racine du dépôt "Pangloss" ?

(lié à #79 )

**Comment by alexis-michaud** [comment]
@vasaura @sguillaume le code intéresse des collègues ; si vous trouviez le temps de ce petit toilettage, ça ne serait pas en vain, je pense ;-)

A vous de voir en fonction du temps disponible et des priorités.

**Comment by vasaura** [comment]
le code est propre ici: https://github.com/sguillaume/DoiPangloss

**Comment by alexis-michaud** [comment]
Ne faudrait-il pas alors supprimer le doublon ? Ce n'est pas utile d'avoir 2 lieux différents, si ?
