### ISSUE TITLE
dépôt nouvelle version document na crdo-NRU_F4_HOUSEBUILDING.xml

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/Pangloss#85]
La nouvelle version du texte est ici : 

https://github.com/alexis-michaud/na/blob/master/TEXT/F4/crdo-NRU_F4_HOUSEBUILDING.xml

(Il y a maintenant une traduction 'lissée' en anglais, et une transcription orthographique, ajoutées par 1 collègue néo-zélandaise.)

Merci bcp !

**Comment by sguillaume** [comment]
Fait.

**Comment by alexis-michaud** [comment]
👍
