### ISSUE TITLE
liste de ressources par nom de chercheur : ne fonctionne plus ?

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/Pangloss#89]
Depuis la page des ressources kakabé

http://pangloss.cnrs.fr/corpus/list_rsc_en.php?lg=Kakabe

en cliquant sur le nom du chercheur, ça donne une liste vide

http://pangloss.cnrs.fr/corpus/search.php?keywords=Vydrina,%20Alexandra

Pas mieux avec ce lien-ci

http://pangloss.cnrs.fr/corpus/search.php?keywords=Ferlus,%20Michel

**Comment by alexis-michaud** [comment]
Je voulais lancer une annonce concernant les données kakabé (mise en "vitrine" virtuelle); pour ça, ce serait idéal que le site soit passé en https (sinon ça fait pas super-sérieux, cf #61 ) et que le lien vers la chercheuse ainsi mise en valeur fonctionne.

**Comment by alexis-michaud** [comment]
Bon, [la pub' est envoyée](https://twitter.com/LaCiToCNRS/status/1150748262711857152), mais la demande reste d'actualité :-)

**Comment by sguillaume** [comment]
Le site que tu regardes est celui que je suis en train de transférer sur huma-num.
C'est donc normal qu'il ne fonctionne pas correctement car il est en cours de migration.
Il faut que tu ailles sur le site du labo car c'est toujours l'emplacement officiel de Pangloss pour le moment. lacito.vjf.cnrs.fr/pangloss/

Voilà voilà !

**Comment by alexis-michaud** [comment]
C'est noté ! merci
