### ISSUE TITLE
Lien avec photos / Connect the Pangloss resources (audio/video) with photos from visual archives

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/Pangloss#90]
La numérisation et l'archivage de photos et diapositives n'ont pour l'instant pas été organisés de façon aussi systématique que pour les ressources linguistiques audio. Mais ce volet du projet de sauvegarde patrimoniale est important lui aussi, et [un fonds d'archives d'images fixes a été mis en place](http://lacito.huma-num.fr/). 

Il serait utile de les relier, pour permettre aux utilisateurs une navigation facilitée entre les diverses composantes des ressources constituées au fil des enquêtes de terrain. Ces ressources comprennent : 
* textes : enregistrements de récits, chants... ; 
* dictionnaires et enregistrements de vocabulaire ; 
* grammaires et publications ; 
* iconographie : photos, diapositives, croquis et dessins ; 
* herbiers... 

(Liste non exhaustive).

**Comment by alexis-michaud** [comment]
Dans le cadre du projet Com'Lab (mise en oeuvre prévue prochainement), qui vise à ce que l'interface soit adaptée au grand public (faire du portail Pangloss un outil dont un large public puisse se servir / puisse aisément consulter), une bonne association entre images et sons serait particulièrement bienvenue. La dimension visuelle joue un grand rôle pour un site internet.

**Comment by alexis-michaud** [comment]
C'est en route.

**Comment by EdouardSombie** [comment]
👍
